### ISSUE TITLE
Processus de migration Prisme vers Docalist

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#137]
Voici un début de proposition pour la migration vers le logiciel Docalist
J'ai mis des dates, à voir entre nous

**Phase de test (juin 2014 – sept 2014)
Site de développement**
- Saisie en ligne au format éclaté de Prisme avec possibilité 
- d’export au format actuel de Prisme (Maju et Riche)
et/ou
- d’export au format éclaté de Prisme (Maju et Riche)
- Remontée des bugs auprès de la commission informatique
- Correction des bugs

**Phase de pré-migration (octobre 2014)**
- Adoption du format éclaté par les membres du réseau Prisme : envoie des mises à jour et export
- Adoption du Thésaurus 2014 par les membres du réseau Prisme
- Choix d’un calendrier des corrections par le réseau Prisme

**Phase de migration (octobre 2014)
Site officiel**
- Mise en ligne définitive de la base de donnée
- Saisie en ligne des nouvelles notices avec statut ‘en attente de correction’
Les membres peuvent exportées les notices crées au format éclaté (Maju et Riche)
ou
Import des notices avec statut ‘en attente de correction’
- Correction par les producteurs des notices, changement des statuts de notice
- Export des notices par les membres du réseau
- Remontée de bugs

**Phase de déploiement (novembre 2014)**
- Création des différentes bases pour les produits Prisme
	Infolégis, Brsm, Annuaire des sites, Répertoire des revues
- Import des données de ces bases si nécessaire

**Comment by daniel-menard** [comment]
Ce ticket date de juin 2014, c'était un calendrier prévisionnel et je pense qu'on peut désormais le fermer : les points techniques ont été faits, le reste ne dépend plus vraiment de nous (adoption par le réseau du nouveau format, du nouveau thésaurus, ...)
