### ISSUE TITLE
Table format

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#177]
Il manque certaines information dans la table format par rapport à la demande de la commission audiovisuelle :
Audiodescription
Bonus
Livret
Sous-titrages sourds et malentendants

**Comment by daniel-menard** [comment]
Discussion du 23/01/2015 : 

Dans la table format :
- on ajoute l'item VOST
- on ajoute un TG "subtitles" et autant de TS "sub-title-xxx" qu'on a de langues de sous-titres à gérer (fra, eng, spa, ger, ita)

**Comment by daniel-menard** [comment]
Fait.

J'ai ajouté VOST avec des "voir aussi" vers VO et VF : 
![image](https://cloud.githubusercontent.com/assets/3940667/5936579/523f297c-a6e6-11e4-9cea-7d14a0e2ab4c.png)

Et j'ai ajouté les entrées sous-titres (même langues que pour les résumés) : 
![image](https://cloud.githubusercontent.com/assets/3940667/5936642/cbe5e356-a6e6-11e4-8b09-2a3840596e0a.png)

*Astuce* : en saisie, si on tape le début du nom de la langue, on obtient directement les "bonnes" étiquettes de collation :

![image](https://cloud.githubusercontent.com/assets/3940667/5936697/627e369c-a6e7-11e4-8301-027d7eb9fa41.png)
