### ISSUE TITLE
Charger la version 2.2 du thesaurus Prisme

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#187]
Le ticket #186 m'a fait repenser à ça : 

> E-mail de Nicolas du 5 juillet 2014 14:03 :
> je vous transmets en PJ le thésaurus de Prisme dans sa dernière version (V.2.1)
> je le mettrai dans le fichier partagé du Drive.

Cette nouvelle version a été envoyée suite aux erreurs détectées dans le ticket #73.
Je crois qu'on a tous un peu zappé... (y'avait pas de ticket !)

**Comment by daniel-menard** [comment]
Nous avons évoqué ce ticket par téléphone le 11/05 : avez-vous pu demander un nouvel export du thesaurus avec les trois corrections demandées ?

**Comment by daniel-menard** [comment]
Vu par téléphone avec Nicolas vendredi soir : 

Plusieurs tentatives de correction "à la source" ont été faites, mais il semble qu'il ne soit pas possible d'obtenir un export propre du thésaurus car le logiciel utilisé pour gérer le thésaurus est incapable d'afficher les termes à corriger (c'est comme s'il ne les connaissait pas). En fait, je pense que c'est la base de données elle-même (celle qui contient le thésaurus) qui est abîmée et donc c'est impossible de supprimer les erreurs. 

Je vais donc faire les corrections manuellement dans le fichier d'export. Pour cela, je vais repartir de l'export fait le 26/11/2014 car les tentatives de corrections faites depuis ont eu pour effet de supprimer des non-descripteurs qui n'avaient pas lieu d'être supprimés.

Pour qu'on soit au clair sur les dénominations, je propose d'intituler cette version "thésaurus prisme 2.2".

**Comment by daniel-menard** [comment]
Je pense être venu à bout de cette version 2.2 du thésaurus !

Une nouvelle table `thesaurus-prisme-2.2` a été créée sur le .net (table prédéfinie). Une fois finalisée, il ne restera plus qu'à l'activer.

**Détail du travail effectué :**

- [X] Génération d'un fichier d'export "propre" à partir de la version du 26 novembre 2014
- [X] Correction des trois erreurs qu'il y avait :
    - [X] AIDE JURIDICTIONNELLE, suppression de USE: AIDE JUDICIAIRE
    - [X] MODE DE GARDE remplacement de RT: STRUCTURE D'ACCUEIL DE LA PETITE ENFANCE par RT: ETABLISSEMENT D'ACCUEIL DU JEUNE ENFANT
    - [X] VOCABULAIRE, suppression de USE: TERMINOLOGIE
- [X] Relecture 
- [X] Corrections d'erreurs liées à la réaccentuation faite pour la version 2.1
    - [X] Éleve ->Elève
    - [X] Éleve surdoué ->Elève surdoué
    - [X] Institut Universitaire de Formation des Maitres -> Maîtres
    - [X] Kinesithéraphie -> Kinésithéraphie
- [X] Adaptation du script de conversion
- [X] Minusculisation et réaccentuation des nouveaux termes de la version 2.2
- [X] Passage des libellés et des descriptions au correcteur orthographique de Libre Office
- [X] Erreurs détectées et corrigées :
    - [X] Caisse Nationale d'Assurance Veillesse : il manque un "i" à veillesse
    - [X] onycophagie -> onychophagie
    - [X] Typo dans la note d'application de "Aide sociale" (g en trop à la fin).
- [X] Tri de la table par code+label pour pouvoir faire un [diff](https://fr.wikipedia.org/wiki/Diff) automatique avec la version précédente.

**Remarques :**

1. J'avais un doute sur l'orthographe de "Ergothérapeuthe" ("Ergothérapeute" est plus courant) mais apparemment les deux graphies sont autorisées, donc je n'ai pas corrigé

2. J'ai été surpris de voir qu'on avait à la fois les descripteurs "Kinésithérapie" et "Kinésithéraphie". Google ne semble pas connaître la version avec un H (non corrigé).

3. Certains termes contiennent des virgules. Comme c'est le séparateur utilisé par prisme dans le champ `DE`, cela peut poser problème. Voici la liste des termes trouvés (non corrigé) : 

    - *non-descripteurs :*
        - Brevet Professionnel Jeunesse, Education Populaire et Sports
        - Diplôme d'Etat Jeunesse, Education Populaire et Sports
        - Diplôme d'Etat Supérieur Jeunesse, Education Populaire et Sports
        - Direction Départementale du Travail, de l'Emploi et de la Formation Professionnelle
        - Direction Régionale de la Jeunesse, des Sports et de la Cohésion Sociale
        - Organisation des Nations Unies pour l'Education, la Science et la Culture
        - Réseaux d'Ecoute, d'Appui et d'Accompagnement aux Parents
    - *descripteurs :*
        - Professions, statuts et catégories professionnelles
        - Titres, diplômes et certificats

**Quelques stats sur cette version 2.2 :**

- Le thésaurus contient 3608 termes (2414 descripteurs, 1194 non-descripteurs)
- 116 termes ont une note d'application
- 525 termes ont un ou plusieurs "voir aussi"
- 1212 termes de premier niveau (i.e. sans TG)
- la longueur moyenne des termes est de 15.6 caractères (13.8 pour les descripteurs, 19.8 pour les non-descripteurs)
- les termes les plus courts font 2 lettres (Ça, Os et QI)
- le terme le plus long fait 101 caractères (Certificat d'Aptitude aux Fonctions de Directeur d'Etablissement ou de Service d'intervention sociale)

**Travail restant à faire :**
- [ ] si vous avez le temps : une petite relecture pour pister les dernières coquilles/typos/erreurs éventuelles
- [ ] voir s'il faut faire quelque chose pour les trois remarques signalées plus haut
- [ ] armer le nouveau thésaurus en saisie (il faut juste modifier les trois tables `prisme-topics` et remplacer `thesaurus:thesaurus-prisme-2013` par `thesaurus:thesaurus-prisme-2.2`).
- [ ] rediscuter du problème éventuel posé par les majuscules accentuées qui sont difficiles à saisir au clavier (par exemple `Éducation` ou `Chef d'État`) et plus généralement des caractères utilisés dans cette version "riche" (ligatures par exemple : `Œdipe`, `Sœur`, etc.) **=> je vais faire un ticket à part pour ça**.

Voila, voila.

**Comment by Nicolas-L** [comment]
Je fait un retour à la com langage pour les Remarques (avec "Urgent").

Pour les virgules, est-ce qu'on peut imaginer de les enlever du Code et de les conserver dans le Label ? (faire comme si c'était une information en plus, sur le même principe que pour les caractères riches).

**Comment by daniel-menard** [comment]
> Pour les virgules, est-ce qu'on peut imaginer de les enlever du Code

Oui c'est envisageable, mais jusqu'à maintenant, j'avais veillé à garder une équivalence "stricte" entre code et label (seule la casse des caractères change).

Je vous laisse décider ;-)

**Comment by Nicolas-L** [comment]
La com langage propose de répondre aux remarques pour jeudi.

**Comment by ocormont** [comment]
Concernant les virgules, je serais d'avis de les remplacer par des tirets.
C'est déjà une règle de saisie au sein du réseau.
Voyons ce que la commission langage propose avant d'acter

**Comment by Nicolas-L** [comment]
Retour de la com langage sur les **Remarques** : 

1. Mettre "Ergothérapeute" en descripteur principal et mettre "Ergothérapeuthe" en Synonyme
2. "Kinesithéraphie" devient "Kinésithérapie"
3. Virgules : 
    - *non-descripteurs :* virgules supprimées
    - *descripteurs :* Ce ne sont en fait pas des descripteurs, ce sont des têtes de champs sémantiques (CS ou MT). Et on ne doit pas indexer avec les CS. Cela pose une question d'ordre technique : Comment on empêche l'indexation avec les CS ?

**Comment by daniel-menard** [comment]
> "Kinesithéraphie" devient "Kinésithérapie"

Impossible : comme indiqué plus haut, on a déjà "Kinésithérapie" comme descripteur
Un avec "MEDECINE" comme TG, l'autre avec "SPECIALITE PARAMEDICALE".

> descripteurs : Ce ne sont en fait pas des descripteurs

Concrètement, je supprime la virgule ou pas ?

> Comment on empêche l'indexation avec les CS ?

Techniquement, ce sont des descripteurs comme les autres, donc rien n'empêche qu'ils ne soient utilisés, si ce n'est le bon sens des documentalistes. 

Traditionnellement pour ce genre de besoins, on utilise des micro-thésaurus.

**Comment by daniel-menard** [comment]
Les corrections à appliquer ont été décidées en réunion téléphonique.

Voici la liste des modifications apportées au fichier thésaurus : 

- Modification du descripteur "Ergothérapeuthe" (avec un H), devient "Ergothérapeute" (sans H)
    - Ajout de "ergothérapeuthe" comme non-descripteur : USE "Ergothérapeute"
    - Modification de "Ergothérapie" : TA "Ergothérapeuthe" remplacé par "Ergothérapeute"

- Suppression du descripteur "Kinésithéraphie" (on a déjà le descripteur "Kinésithérapie")
    - Et donc suppression implicite du TS "Kinésithéraphie" qu'on avait pour "Spécialité médicale"
    - Modification du TG de Kinesithérapie : MEDECINE -> SPECIALITE PARAMEDICALE

- Suppression de la virgule dans le libellé des non-descripteurs suivant : 
    - Brevet Professionnel Jeunesse[,] Education Populaire et Sports
    - Diplôme d'Etat Jeunesse[,] Education Populaire et Sports
    - Diplôme d'Etat Supérieur Jeunesse[,] Education Populaire et Sports
    - Direction Départementale du Travail[,] de l'Emploi et de la Formation Professionnelle
    - Direction Régionale de la Jeunesse[,] des Sports et de la Cohésion Sociale
    - Organisation des Nations Unies pour l'Education[,] la Science et la Culture
    - Réseaux d'Ecoute[,] d'Appui et d'Accompagnement aux Parents
    
- Suppression de la virgule dans le CS "Professions[,] statuts et catégories professionnelles" (code et libellé) et correction du TG pour les termes : 
    - Agriculteur
    - Aidant familial
    - Aide éducateur
    - Aide médico-psychologique
    - Aide soignant
    - Animateur
    - Animateur socioculturel
    - Artisan
    - Artiste
    - Assistant de service social
    - Assistant familial
    - Assistant maternel
    - ATSEM
    - Auxiliaire de justice
    - Auxiliaire de puériculture
    - Auxiliaire de vie scolaire
    - Auxiliaire de vie sociale
    - Avocat
    - Avocat d'enfant
    - Cadre
    - Cadre de l'intervention sociale
    - Chef de service éducatif
    - Chercheur
    - Chirurgien dentiste
    - Comédien
    - Commerçant
    - Conseiller conjugal
    - Conseiller d'orientation
    - Conseiller en économie sociale et familiale
    - Conseiller principal d'éducation
    - Conseiller technique et pédagogique
    - Conseiller technique régional
    - Coordonnateur
    - Défenseur des droits
    - Défenseur des enfants
    - Délégué à la tutelle
    - Directeur d'établissement
    - Documentaliste
    - DRH
    - Éducateur de jeunes enfants
    - Éducateur de justice
    - Éducateur de rue
    - Éducateur scolaire
    - Éducateur spécialisé
    - Éducateur technique spécialisé
    - Employé familial
    - Employé familial polyvalent
    - Enseignant
    - Ergothérapeute
    - Expert
    - Expert judiciaire
    - Formateur
    - Greffier
    - Huissier de justice
    - Infirmier
    - Infirmier psychiatrique
    - Inspecteur du travail
    - Instituteur spécialisé
    - Juge aux affaires familiales
    - Juge d'instance
    - Juge d'instruction
    - Juge d'instruction des mineurs
    - Juge de l'application des peines
    - Juge de proximité
    - Juge des enfants
    - Juge des tutelles
    - Magistrat
    - Mandataire judiciaire
    - Médecin
    - Médecin-conseil
    - Médiateur
    - Médiateur de la république
    - Médiateur familial
    - Médiateur national
    - Moniteur d'atelier
    - Moniteur éducateur
    - Orthophoniste
    - Praticien
    - Professeur des écoles
    - Profession médicale
    - Profession paramédicale
    - Professionnel de l'enfance
    - Psychanalyste
    - Psychiatre
    - Psychologue
    - Psychologue clinicien
    - Psychomotricien
    - Psychothérapeute
    - Puéricultrice
    - Réfèrent
    - Sage-femme
    - Sociologue
    - Surveillant de prison
    - Technicien de l'intervention sociale et familiale
    - Thérapeute
    - Travailleur social
    
- Suppression de la virgule dans le CS "Titres[,] diplômes et certificats" (code et libellé)
  et correction du TG pour les termes : 
    - BPJEPS
    - CAFDES
    - CAFERUIS
    - CAP
    - CAP petite enfance
    - CEFP
    - Certificat d'aptitude
    - CQFMA
    - DEAF
    - DEAMP
    - DEASS
    - DEAVS
    - DECESF
    - DEEJE
    - DEES
    - DEETS
    - DEIS
    - DEJEPS
    - DEME
    - DEMF
    - DESJEPS
    - DSTS

**Comment by daniel-menard** [comment]
Le thesaurus version 2.2 a été "armé en saisie" pour toutes les grilles.

Les tables personnalisées suivantes ont été modifiées :
- prisme-topics
- prisme-topics-web
- prisme-topics-these

J'ai fait la modif à la fois sur le .org et le .net.

**Comment by daniel-menard** [comment]
Et bien il semble que ce ticket soit enfin bouclé !
