### ISSUE TITLE
Réglage Grille de saisie dans Base Prisme du .net / BUG

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#195]
En rechargeant la dernière bdd (6/10) de la Base Prisme dans le .NET, puis en voulant régler le format d'affichage court du type de notice Livre, j'ai effectué une manip qui a bloqué l'accès au réglage du formulaire de saisie et qui rend impossible l'accès à la saisie de nouvelles notices de livre.

Explication de la mauvaise manip : 

En important la nouvelle base, je me suis apperçu que le champ indexation (sauf pour Articles) était sur la table topics et non prisme-topics (normal puisqu'on n'avait pas reparamétré les champs).
Sachant que les réglages n'avaient pas étés encore effectués, j'ai voulu faire un exercice pour moi sur le type de notice Livre. J'ai changé la configuration et appliqué la table prisme-topics pour le formulaire de saisie, l'affichage long et court.
Les mots clés se sont donc affichés en minuscule sur la grille de saisie (ils étaient en rouge maju => bleu minu), à l'affichage long, mais pas pour l'affichage court où ils sont restés en maju.

La mauvaise manip est la suivante : 

Je ne sais plus pour quelle raison exactement, et après quelques autres tentatives infructueuses, j'ai voulu revenir sur la table topic initialement paramétrée sur le formulaire de saisie de Livre. Mais tous les vocabulaires sont restés quand même affichés dans le champ (après enregistrement du passage prisme-topics => topics). J'ai voulu ensuite remettre la table prisme-topics, puis enregistré. C'est à partir de là que le message d'erreur est apparu.

Donc : 

- impossible de revenir sur le réglage de la grille de saisie Livre (Base Prisme du .NET) : 
Fatal error: Call to undefined method Docalist\Type\String::editSettings() in /var/www/documentation-sociale.net/plugins/docalist-biblio/views/grid/edit.php on line 163

- impossible de saisir une nouvelle notice de Livre sur la base ni d'atteindre la grille de saisie d'une notice de Livre déjà enregistrée : 
Fatal error: Call to undefined method Docalist\Type\String::editForm() in /var/www/documentation-sociale.net/plugins/docalist-biblio/class/Pages/EditReference.php on line 425

**Comment by daniel-menard** [comment]
Je pense qu'on peut enfin fermer ce fameux bug 195 !

(cf. #222)
