### ISSUE TITLE
Auteur d'une notice

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#197]
Lorsque l'on modifie une notice créée par une personne, le correcteur devient Auteur de la notice.
Je ne sais pas si cela peut avoir un impact sur notre manière de travailler. Si je veux retrouver une notice que j'ai faite, si un correcteur l'a modifié, je ne pourrais pas la retrouver...

**Comment by daniel-menard** [comment]
Corrigé (à tester).
