### ISSUE TITLE
Modification d'une notice et affichage

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#198]
Lorsque l'on modifie une notice, sa date est modifié et est considérée comme dernière notice créée. Elle apparait donc en premier en affichage court.
Ce comportement n'est pas logique (pour moi) car on perd l'historicité des créations de notice dans la base.
Est ce que cela aura aussi des incidences lors de l'export ?

**Comment by daniel-menard** [comment]
Corrigé (à tester).
