### ISSUE TITLE
Embed vidéo

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#205]
**Suite au commentaire de Laurent (mail du 21/10 sur discuss-prisme) :**

> Est-ce que les liens type bande-annonce, site tiers pourraient s'ouvrir sur une autre page quand on clique dessus ?

En regardant l’exemple de sa notice : http://www.documentation-sociale.net/tests/31/ et le lien vers la bande annonce (http://goo.gl/fgRseN), je m’aperçois que la vidéo n’est pas incluse dans la notice comme le serait une vidéo Youtube. Or, le site (allo ciné) qui héberge la vidéo signalée propose bien une fonctionnalité embed : « exporter => publier cette vidéo sur mon blog ».

**A partir de là je remarque dans Docalist :**

- que si je prends une partie du code (exporter) <iframe src="http://www […] contenant l’adresse exacte de la vidéo et que j’en arrange la taille à ma convenance,
- que je le copie/colle sur le formulaire de saisie de Docalist dans une zone de texte du champ « de quoi parle le film ? »

![ex1](https://cloud.githubusercontent.com/assets/5398758/4836625/6b637a18-5fc7-11e4-8959-fc28d505c04e.jpg)

**==> la vidéo est bien affichée dans le corps de la notice comme le serait une vidéo Youtube.** voir ci-dessous

![ex2](https://cloud.githubusercontent.com/assets/5398758/4836630/79d5b0de-5fc7-11e4-9bb5-3f0b77f56ce8.jpg)

**Questions :**

1. Est-ce qu’il ne serait pas possible d’avoir cette fonctionnalité (embed vidéo) dans le champs « lien internet » qui permettrait de renseigner des balises *iframe* avec le lien exact de la vidéo pour l'afficher directement dans la notice ?

2. Est-ce que ce champ (contenu du document) ne devrait pas être strictement « texte », et ne tolérer aucun code ? En fait je me demande si un producteur *lambda* ayant remarqué cette possibilité de mettre en forme du texte via l’usage de codes (balises, etc.) ne serait pas tenté de le faire, et si il le faisait : quelles conséquences sur la notice exportée ?

**Comment by daniel-menard** [comment]
Comme vu par téléphone, il y a deux aspects dans vos questions :

**1. Embed allocine**

J'ai développé un plugin qui permet "'d'apprendre" à wordpress comment incorporer une bande annonce allociné en copiant simplement son url dans le champ lien. 

J'ai testé avec quelques films et cela semble fonctionner mais c'est bien sur à tester et je ne garantis pas que ça marche dans 100% des cas (mais si jamais ça ne marchait pas, on obtiendra simplement une lien cliquable).

**2. Champ strictement texte**

Vous avez tout à fait raison : le champ `content` ne devrait accepter que du texte (sauf si on souhaite faire de la mise en forme dans les résumés, dans ce cas il faudrait que ce soit une option). De même, le champ link ne devrait accepter que des [URI](http://fr.wikipedia.org/wiki/Uniform_Resource_Identifier) et des URL valides, etc.

Tout cela relève du chapitre "contrôles" de saisie : pour le moment, il n'y en a aucun.

**Comment by Nicolas-L** [comment]
Le plugin Docalist Allocine Embed fonctionne très bien !

Petite remarque : Il faut bien mettre l'url de la page Allociné et non le code d'embed proposé par Allociné (dans ses options de partage).
Dans ce dernier cas, la vidéo est tout de même incorporée à la notice longue mais le lien de la notice **format court** renvoie vers une erreur 404.

**Comment by daniel-menard** [comment]
Oui, c'est bien une url qu'il faut saisir (et rien d'autre) et non pas le code d'intégration html/javascript différent par le site.

En fait le but de [oEmbed](http://oembed.com/) (c'est le nom officiel du protocole) c'est justement d'éviter que chaque site propose un code d'intégration différent qu'il faut copier/coller. Avec oEmbed, on saisit uniquement l'url de la page ou du média à incorporer et derrière le plugin génère dynamiquement et de manière transparente le code nécessaire pour l'intégration.

C'est beaucoup plus simple pour l'utilisateur et il y a moins de risque d'erreur mais surtout, c'est bien plus évolutif : quand on n'utilise pas oEmbed, si un jour le code d'intégration change (évolution du site, nouvelle adresse, etc.), il faut reprendre et modifier une par une toutes les notices... Avec oEmbed, comme c'est dynamique et qu'on a saisit que l'url, il suffit d'adapter le plugin et tout est mis à jour automatiquement.

PS : pour l'erreur 404 qu'on obtient si on saisit du code html, c'est normal puisque le champ est prévu pour gérer une url et rien d'autre.

**Comment by Nicolas-L** [comment]
> Oui, c'est bien une url qu'il faut saisir (et rien d'autre) et non pas le code d'intégration html/javascript différent par le site.

C'est pas tout à fait le sujet mais j'en profite pour signaler que les liens `courriel` renvoient aussi vers du 404 (format court et long) sur ce champ

**Comment by daniel-menard** [comment]
Dernière remarque de Nicolas : cf. ticket #231.
