### ISSUE TITLE
Mise à jour du site .net du 27/01/2015

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#222]
Le site .net a été mis à jour, merci de tester !

Voici la liste des corrections apportées :

**Corrections de bugs :**

- #197 : quand on modifie une notice saisie par quelqu'un d'autre, on devient l'auteur de la notice.
- #198 : quand on modifie une notice, ça change la date de création de la notice et celle-ci apparaît comme une notice fraîchement créée.
- #210 : les valeurs par défaut définies dans la grille formulaire sont ré-appliquées lorsqu'on édite une notice.
- #211 : On ne peut pas modifier le statut d'une notice, dès qu'on enregistre la notice passe en statut `publish`.
- (pas de ticket) : dans la table "links", le code utilisé pour "url" a été corrigé (on avait G01 mais Prisme utilise le code "url" dans les tables personnalisées). Il faudra revoir les autres codes de la table prédéfinie.

**Améliorations diverses :**

- Les bases docalist ont maintenant une icone spécifique dans le menu (avant elles utilisaient la même icone que articles)
- Amélioration du filtrage des champs vides lors de l'enregistrement des notices (suite du ticket #213).

**Nouvelles fonctionnalités :**

- Embed allociné (#205) : un nouveau plugin (Docalist Allocine Embed) a été créé pour permettre d'incorporer les bandes annonces allocine.
- Liste des notices : l'écran a été revu pour permettre de mieux voir la date de création (qui, quand) et la date de modification (idem) de la notice et on peut désormais trier par date de dernière modification (c'est un peu lent mais ça fonctionne).
![image](https://cloud.githubusercontent.com/assets/3940667/5924886/b91b2510-a65f-11e4-8828-5d2ec20e9ac5.png)
- On peut maintenant afficher la liste des notices en mode "détail" : les notices sont alors affichées en utilisant la grille "format court". Le choix est conservé dans les préférences utilisateurs et s'appliquent à toutes les bases.
![image](https://cloud.githubusercontent.com/assets/3940667/5924973/7037c53c-a660-11e4-9e29-8b1cd7ae06c0.png)
- Début du travail sur l'export (#135) : déclaration des formats disponibles, interface côté back-office, etc. Pour le moment, export/affichage en format docalist uniquement.
![image](https://cloud.githubusercontent.com/assets/3940667/5926090/b0071048-a668-11e4-84d4-7c8f23eccfeb.png)

**Comment by ocormont** [comment]
En lien avec le #210 : les valeurs par défaut définies dans la grille formulaire sont ré-appliquées lorsqu'on édite une notice.
Désormais, lorsque nous créons une notice et l'enregistrons, si nous revenons dessus, les types de valeurs par défaut fixés dans les grilles de saisie ne sont plus présents. Par contre les valeurs ne sont pas réinjectés.

Avant enregistrement :
![capture](https://cloud.githubusercontent.com/assets/5398792/6226025/93a22120-b691-11e4-94a3-0944c822d107.JPG)

Après enregistrement :
![capture2](https://cloud.githubusercontent.com/assets/5398792/6226028/9bc98c3a-b691-11e4-8d04-bb971657acc4.JPG)

**Comment by ocormont** [comment]
en lien avec  #197 : quand on modifie une notice saisie par quelqu'un d'autre, on devient l'auteur de la notice.
Lorsque nous créons une notice (test sur base Test et Annuaire des sites), l'auteur de la notice est toujours agaussel.
Si nous revenons sur la notice pour la modifier, le bon auteur de la modification est le bon.

Avant enregistrement : en haut à droite pour le nom
![capture3](https://cloud.githubusercontent.com/assets/5398792/6226181/e4c67136-b692-11e4-9d72-29ebed3b0c8e.JPG)

Après enregistrement :
![capture4](https://cloud.githubusercontent.com/assets/5398792/6226185/ed25f8f6-b692-11e4-9350-27a15f23f17c.JPG)

Après modification : 
![capture5](https://cloud.githubusercontent.com/assets/5398792/6226191/f78f382a-b692-11e4-9154-2d722d1a728e.JPG)

**Comment by daniel-menard** [comment]
Vu par téléphone avec Olivier : 

**[Premier commentaire](https://github.com/daniel-menard/prisme/issues/222#issuecomment-74641017)**

C'est le comportement attendu, tel que je l'ai programmé suite aux différents tickets qu'on avait : 

- Les valeurs par défaut définies dans la grille de saisie sont appliquées uniquement lorsque l'on crée une notice depuis le back-office. Elles ne sont pas appliquées lorsqu'on modifie une notice, ni lors de l'import.
- Lorsqu'on enregistre une notice (que ce soit après création ou après modification), les champs vides sont filtrés et sont supprimés de la notice. La définition exacte de ce qu'est un champ vide dépend du champ (cf. [doc dans commentaire du ticket 173](https://github.com/daniel-menard/prisme/issues/173#issuecomment-57090584)).
- En usage "normal" (on crée une notice complète et on la publie), ce comportement est correct. Par contre, c'est gênant lorsqu'on commence à saisir une notice et qu'on n'a pas le temps de la terminer car lorsqu'on revient dessus pour la compléter, on n'a plus les valeurs par défaut qui étaient proposées lors de la saisie initiale.
- Une amélioration possible (à étudier) serait de ne pas filtrer les champs vides lorsque la notice est enregistrée en mode "brouillon" (i.e. de ne faire le filtrage qu'au moment où la notice passe en statut pending ou publish). Remarque : si on fait ça, l'affichage obtenu en prévisualisation contiendra les champs vides et je pense qu'il y a aussi un impact si la notice est indexée dans ES, donc à étudier.

**[Second commentaire](https://github.com/daniel-menard/prisme/issues/222#issuecomment-74642251)**

C'est un bug qui n'existait pas avant et qu'il faut corriger.

C'est lié à la metabox "Auteur" qui n'est pas correctement initialisée. Par défaut elle n'est pas affichée (il faut aller dans les options de l'écran pour l'activer), mais elle est tout de même prise en compte par WordPress (même si elle est masquée).

Comme elle n'est pas correctement initialisée, c'est le premier compte qui existe qui est pris comme auteur de la notice (agaussel en l’occurrence).

**Comment by daniel-menard** [comment]
Le bug "agaussel" est maintenant corrigé : quand on crée une notice, elle est bien attribuée à l'utilisateur en cours et non "au premier de la liste" comme c'était le cas : 

![image](https://cloud.githubusercontent.com/assets/3940667/6233760/8a3a427c-b6d5-11e4-8239-ef0d220c5705.png)

Du coup, je referme ce ticket !
