### ISSUE TITLE
Erreur dans la table personnalisée Prisme-format

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#223]
Il y a une erreur dans la table personnalisée Prisme-format : 

![image](https://cloud.githubusercontent.com/assets/3940667/5936148/17c50cca-a6e2-11e4-8713-a64b48daf247.png)

Le terme `discography`, qui existe dans la table prédéfinie a été supprimé dans la table prisme personnalisée mais plusieurs termes (`bibliography`, `filmography`, `webography`) ont des "voir aussi" (colonne RT) vers `discography`, d'où l'erreur qui s'affiche.

Partant de là, deux solutions : 

- réintroduire le terme `discography` dans la table personnalisée
- supprimer les voir aussi

**Comment by ocormont** [comment]
C'est rectifié
![image1](https://cloud.githubusercontent.com/assets/5398792/5938140/715a00e0-a6f8-11e4-967b-59d4c01bc1d8.jpg)
