### ISSUE TITLE
Type Périodique

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#224]
La grille Périodique ne contient pas le champ AUCO (Organisme auteur)

**Comment by daniel-menard** [comment]
Lorsqu'on avait revalidé l'ensemble des grilles en septembre dernier, on avait décidé d'enlever le champ `organisation`de la grille `periodical`, mais je suis d'accord que c'est légitime de l'avoir et je ne me souviens plus des raisons pour lesquelles on l'avait supprimé.

J'ai donc réintroduit le champ dans la grille prédéfinie docalist.

Pour les nouvelles bases de données qui seront créées, le champ apparaîtra automatiquement. Par contre, pour les bases existantes qui contiennent déjà le type "périodique" (bases `prisme` et `tests de saisie`), vous allez devoir faire la mise à jour manuellement et refaire le paramétrage des grilles.

Pour cela, il faut supprimer le type `periodical` puis le ré-ajouter et refaire le paramétrage des grilles (avant de supprimer, faites un inventaire des modifs pour pouvoir refaire le même paramétrage ou bien ouvrez deux fenêtres de navigateur pour comparer avant/après).

Remarque : une fois que c'est fait pour une des bases, vous pouvez utiliser l'import/export de paramètres pour faire la même chose sur l'autre.

PS : je vous laisse le soin de fermer ce ticket une fois que c'est fait :-)

**Comment by ocormont** [comment]
En voulant faire les modifications, je me suis aperçu qu'il manque aussi le champ pour indiquer la périodicité de la revue (edition dans docalist).
A moins que nous ayons décider de mettre cette info ailleurs ?

**Comment by daniel-menard** [comment]
Je ne me rappelle plus ce qu'on avait décidé, mais je ne pense pas que ce soit un oubli : dans mes tableaux, le champ edition est bien marqué en "on supprime" pour le type Periodical.

Peut-être le champ format ? (mensuel, trimestriel, etc.)

Sinon, pour le type periodical-issue (numéro de revue), on a bien le champ edition, qui lui permettra d'indiquer "janvier-mars 2015" par exemple.

**Comment by ocormont** [comment]
ok pour le champ format.
Il faudrait donc ajouter dans la table :
bihebdomadaire;
hebdomadaire;
bimensuel;
mensuel;
bimestriel;
trimestriel;
quadrimestre;
semestriel;
annuel;
biennal ou bisannuel;
Source : http://fr.wikipedia.org/wiki/Publication_p%C3%A9riodique

Peut être ajouter un item "parution irrégulière"

**Comment by daniel-menard** [comment]
Pour vous permettre d'avancer sur le ticket #260, je voulais ajouter les entrées de périodicité qui manquent dans la table format, mais même ça c'est compliqué !

Le préfixe "bi" est ambigu car il peut signifier : 
- "deux fois" (du latin *bi* qui a donné *bis*)
- "tous les deux" (du latin *bini*)

Ainsi, bimensuel, peut signifier indifféremment "deux fois par mois" ou "tous les deux mois" (cf. [wiktionary](http://fr.wiktionary.org/wiki/bimensuel)). Les deux sont aussi acceptables l'un que l'autre : ça dépend du contexte.

Dans le monde de l'édition, on a essayé de lever l’ambiguïté en employant "bimestriel" pour désigner "tous les deux mois" et "bimensuel" pour dire "deux fois par mois", mais pour le commun des mortels, ce n'est pas forcément évident.

Le même problème se pose en français pour tous les termes en bi ou en tri.

En anglais, c'est encore plus ambigu car ça peut différer selon qu'on utilise l'anglais américain ou l'anglais britannique !

Par exemple, "biweekly" peut dire indifféremment "deux fois par semaine" ou "toutes les deux semaines". Du coup, les britanniques utilisent plutôt "fortnightly" pour dire "toutes les deux semaines" et dans ce cas, "biweekly" voudra plutôt dire "deux fois par semaine". Mais de leur côté, les américains utilisent plutôt "semiweekly" pour dire "deux fois par semaine" et dans ce cas, "biweekly" sera utilisé pour dire "toutes les deux semaines"...

Bref, pas simple !

Pour que ce soit plus facile à comprendre dans notre table d'autorité, je propose d'éviter ces termes et d'utiliser à la place des expressions qui indiquent le nombre d’occurrences sur une période donnée ou le délai écoulé entre deux parutions.

Ça nous donnerait : 

- deux fois par semaine, 
- toutes les semaines, 
- deux fois par mois, 
- tous les mois, 
- tous les deux mois, 
- tous les trois mois, 
- tous les quatre mois, 
- tous les six mois, 
- tous les ans, 
- tous les deux ans.

Comme la table `format` est au format thesaurus, rien ne nous empêche d'utiliser des "EM" pour faire des renvois si on le souhaite (par exemple : *quotidien : utiliser "tous les jours"*).

Je trouve que la liste obtenue est plus facilement compréhensible par un quidam (le mot quadrimestriel, par exemple, je ne l'emploie pas tous les jours !) et on en déduit facilement le nombre de numéros attendus par an (ça peut être utile pour pointer les numéros et faire du bulletinage, etc.)

Enfin, la liste obtenue est facilement extensible : si on avait besoin d'indiquer "tous les huit mois", par exemple, on peut le faire sans "créer" le terme "octomestriel". On peut également ajouter facilement une entrée comme "Cinq fois par semaine" pour un quotidien qui ne paraît pas le week-end ou "dix fois par an" pour un mensuel non publié pendant l'été.

Qu'en pensez-vous ?

Dernier point : je pense qu'on pourrait étendre un peu le champ d'application de la liste. Avec les entrées qu'on a, on décrit bien les parutions des périodiques, mais on peut imaginer que les mêmes étiquettes soient utilisées pour décrire des émissions de TV, de radio, des événements récurrents, des podcasts, etc.

Du coup, on pourrait avoir des étiquettes comme "toutes les nuits", "toutes les heures", etc.

De même, on pourrait peut-être être plus précis pour décrire les hebdomadaires en ayant des étiquettes comme "tous les lundis", "tous les mardis", etc. Au final, on sait que c'est un hebdomadaire, mais on a plus d'information car on a "encodé" le jour de parution. 

Si on hiérarchise la table, ces étiquettes iront très bien comme TS du descripteur "tous les jours".

A nouveau, qu'en pensez-vous ?

---

Ressources : 
- [Dublin Core Collection Description Frequency Vocabulary](http://dublincore.org/groups/collections/frequency/)
- [Codes utilisés en Unimarc](http://multimedia.bnf.fr/unimarcb_trad/B110-6-2010.pdf)
- [Codes utilisés en Marc21](http://www.loc.gov/marc/bibliographic/concise/bd008s.html)
- [Une liste de termes assez complète sur vocabulary.com](http://www.vocabulary.com/dictionary/periodical)

**Comment by ocormont** [comment]
ok pour moi

**Comment by daniel-menard** [comment]
J'ai fait la table des périodicité sur le modèle évoqué dans le commentaire précédent.

La table est gérée comme un "mini thesaurus", globalement, elle a la structure suivante : 

```
- Publication périodique ou événement récurrent
    - Périodicité inconnue
      (pas de TS pour le moment)
    - Mise à jour en continu
      (là encore pas de TS pour le moment)
    - Périodicité irrégulière
      (pas de TS non plus mais on pourrait avoir des entrées du style "environ 10 par an")
    - Périodicité régulière
        - plusieurs fois par an
          (un par an, deux par an... ; douze par an + 1 HS...)
        - plusieurs fois par mois 
          (un par mois etc.)
        - plusieurs fois par semaine 
          (un par semaine, deux... ; tous les lundis... ; le week-end, en semaine)
        - plusieurs fois par jour
          (un par jour, deux... ; jour / nuit ; matin/midi/soir)
        - plusieurs fois par heure
        - pluriannuel
          (tous les 2 ans, etc.)
        - tous les X mois
        - toutes les X semaines
        - tous les X jours
```

Au final, ça nous fait beaucoup d'entrées, mais je pense qu'on "couvre" bien tout ce qui peut nous tomber dessus comme périodicité exotique. Certaines entrées vous sembleront farfelues et ne seront certainement jamais utilisées pour de la documentation, mais pourraient avoir un sens si on cataloguait des trucs très différents (journal TV, durées de baux ou de contrats, éruptions de volcans, épidémies...)

Pour faire cette table, les pages suivantes m'ont été très utiles (j'ai appris de nouveaux mots !) : 
- https://www.druide.com/enquetes/adjectifs-de-périodicité
- https://www.druide.com/enquetes/periodicite-inusitee

Voici le lien vers le fichier de travail que j'ai utilisé pour réaliser la table : 

- [doc google drive - accès restreint](https://docs.google.com/spreadsheets/d/1xXVm3fxRdwjxTKPbf04aQXhjerVgoxH47v9L3bU8kE8/edit?usp=sharing)

N'hésitez-pas à me dire ce que vous en pensez et à me signaler les incohérences et coquilles éventuelles.

**Remarques et subtilités :**

- A chaque fois, j'ai considéré que "1" était compris dans "plusieurs". 
  L'entrée "1 par mois", par exemple, figure en TS de "plusieurs fois par mois"
  C'est un peu contre-intuitif, mais ça permet de garder les entrées "1/2/3/4 par mois" ensembles.
  En fait, le "plusieurs fois" doit à chaque fois être compris comme "une ou plusieurs fois"
- On a à la fois "quatre par mois" et "un par semaine" : au début, je les avais
  mis en synonymes, mais "quatre par mois" nous donne 48 numéros par an alors que 
  "un par semaine" nous donne 52 numéros par an, et on trouve effectivement des revues
  qui font la différence ! (pour du bulletinage, par exemple, ça peut avoir de l'importance)
- Idem pour d'autres : par exemple "deux par mois" différent de "toutes les 2 semaines"
- J'ai mis presque partout en description le nombre de numéros par an.
- J'ai ajouté toutes les entrées usuelles (annuel, mensuel, hebdomadaire...) comme synonymes, ce qui fait qu'elles sortent dans la liste quand on les cherche
- Inversement, j'ai ajouté des entrées, même s'il est peu probable qu'on les utilise, quand il existait un mot de la langue française pour désigner ces durées (cf. page druide ci-dessus) : décadaire, sesquimestriel, semi-millennal, etc.)
- Les codes et les libellés ont été "travaillés" pour faciliter la recherche : on peut commencer soit en tapant une durée ("an" par exemple), soit un nombre de numéros. A chaque fois on a toutes les entrées correspondantes. Les nombres peuvent être saisis soit en chiffres (les codes contiennent les chiffres) soient en lettres (les libellés contiennent les ordinaux). Ce sera plus facile à voir quand ce sera en ligne.
- J'ai essayé d'avoir plein de "voir aussi" (colonne RT) pour inciter les gens à être précis lors de la saisie.

PS : si vous me trouvez une revue qui ne rentre pas dans la liste, je mange mon chapeau !

**Comment by daniel-menard** [comment]
Je ferme ce ticket, on en ouvrira un nouveau si des erreurs sont détectées dans la table des périodicités.
