### ISSUE TITLE
Table format

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#226]
Il n'y a pas de termes génériques pour les documents électroniques, audio ou vidéo en ligne.
Pour le résumé, la Vost, nous avons les termes génériques.
Il serait peut être judicieux d'ajouter les termes `Document électronique` `audio en ligne` `vidéo en ligne`

| code      | label                      | description                                                                                             |
|-----------|----------------------------|---------------------------------------------------------------------------------------------------------|
| pdf       | document PDF               | Document électronique en format PDF.                                                                    |
| html      | page HTML                  | Document électronique en format HTML.                                                                   |
| xml       | fichier XML                | Document électronique en format XML.                                                                    |
| doc       | document Word 97-2003      | Document électronique en format Microsoft Word 97/2000/XP/2003.                                         |
| docx      | document Word 2007 et plus | Document électronique en format Microsoft Word 2007 ou ultérieur.                                       |
| rtf       | document RTF               | Document électronique en format RTF (Rich Text Format).                                                 |
| odt       | texte OpenDocument.        | Document électronique en format Open Document Text (Oasis, Open Office, Libre Office, etc.)             |
| odp       | présentation OpenDocument  | Présentation électronique au format Open Document Presentation (Oasis, Open Office, Libre Office, etc.) |
| ppt       | présentation PowerPoint    | Présentation électronique au format Microsoft PowerPoint.                                               |
| zip       | archive ZIP                | Archive compressée au format ZIP                                                                        |
| jpeg      | image JPEG                 | Photo ou image au format JPEG.                                                                          |
| png       | image PNG                  | Photo ou image au format PNG.                                                                           |
| mp3       | audio au format MP3        | Document audio au format MP3.                                                                           |
| wma       | audio WMA                  | Document audio au format WMA.                                                                           |
| mpeg      | vidéo MPEG                 | Vidéo au format MPEG.                                                                                   |
| mp4       | vidéo MP4                  | Vidéo au format MP4.                                                                                    |
| quicktime | vidéo QuickTime            | Vidéo au format QuickTime (QT).                                                                         |
| wmv       | vidéo WMV                  | Vidéo au format Windows Media Player.                                                                   |
| avi       | vidéo AVI                  | Vidéo au format AVI.                                                                                    |

**Comment by daniel-menard** [comment]
Fait, j'ai créé l'arborescence suivante (un vrai petit thésaurus !) : 

```csv
computer-file;"fichier informatique";;;;;"Fichier informatique.";"Utiliser de préférence l'un des termes spécifiques pour décrire précisément le format (pdf, jpeg, avi...)";
    electronic-document;"document numérique";;;computer-file;;"Document électronique.";"Utiliser de préférence l'un des termes spécifiques pour décrire précisément le format (pdf, zip, avi...)";
        pdf;"document PDF";;;electronic-document;;"Document électronique en format PDF.";;
        html;"page HTML";;;electronic-document;;"Document électronique en format HTML.";;
        xml;"fichier XML";;;electronic-document;;"Document électronique en format XML.";;
        doc;"document Word 97-2003";;;electronic-document;;"Document électronique en format Microsoft Word 97/2000/XP/2003.";;
        docx;"document Word 2007 et plus";;;electronic-document;;"Document électronique en format Microsoft Word 2007 ou ultérieur.";;
        rtf;"document RTF";;;electronic-document;;"Document électronique en format RTF (Rich Text Format).";;
        odt;"texte OpenDocument";;;electronic-document;;"Document électronique en format Open Document Text (Oasis, Open Office, Libre Office, etc.)";;
        odp;"présentation OpenDocument";;;electronic-document;;"Présentation électronique au format Open Document Presentation (Oasis, Open Office, Libre Office, etc.)";;
        ppt;"présentation PowerPoint";;;electronic-document;;"Présentation électronique au format Microsoft PowerPoint.";;
        zip;"archive ZIP";;;electronic-document;;"Archive compressée au format ZIP";;
    digital-image;"image numérique";;;computer-file;;"Image au format numérique.";"Utiliser de préférence l'un des termes spécifiques pour décrire précisément le format (jpeg, png...)";
        jpeg;"image JPEG";;;digital-image;;"Photo ou image au format JPEG.";;
        png;"image PNG";;;digital-image;;"Photo ou image au format PNG.";;
    audio-file;"fichier son";;;computer-file;;"Fichier son.";"Utiliser de préférence l'un des termes spécifiques pour décrire précisément le format (mp3, wma...)";
        mp3;"audio au format MP3";;;audio-file;;"Document audio au format MP3.";;
        wma;"audio WMA";;;audio-file;;"Document audio au format WMA.";;
    video-file;"fichier vidéo";;;computer-file;;"Fichier vidéo.";"Utiliser de préférence l'un des termes spécifiques pour décrire précisément le format (mpeg, avi, quicktime, wmv...)";
        mpeg;"vidéo MPEG";;;video-file;;"Vidéo au format MPEG.";;
        mp4;"vidéo MP4";;;video-file;;"Vidéo au format MP4.";;
        quicktime;"vidéo QuickTime";;;video-file;;"Vidéo au format QuickTime (QT).";;
        wmv;"vidéo WMV";;;video-file;;"Vidéo au format Windows Media Player.";;
        avi;"vidéo AVI";;;video-file;;"Vidéo au format AVI.";;
```

![image](https://cloud.githubusercontent.com/assets/3940667/6235449/c7888348-b6e2-11e4-8e01-1a1b277e5491.png)

*Remarques :* 
- Je n'ai pas repris la notion de "en ligne" qui figurait dans vos suggestions : au niveau de la table format, on ne sait pas si le document est en ligne, stocké sur un dvd, une tablette, etc.
- J'ai fait les modifs dans la table prédéfinie `format`, je vous laisse le soin de faire un copier/coller vers la table `prisme-format`.
