### ISSUE TITLE
Impression des pages wordpress

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#227]
Les feuilles de style d'impression du site wordpress ne fonctionnent pas

![capture](https://cloud.githubusercontent.com/assets/5398792/6211663/e4a2607c-b5dc-11e4-8207-71c21d3be5c1.JPG)
![capture2](https://cloud.githubusercontent.com/assets/5398792/6211664/e618d508-b5dc-11e4-912a-2427f8706c52.JPG)
![capture3](https://cloud.githubusercontent.com/assets/5398792/6211670/eafbc42c-b5dc-11e4-9519-a8f1bd4c5f6d.JPG)

**Comment by daniel-menard** [comment]
Évoqué avec Olivier par téléphone.

- Le thème Prisme utilise comme styles de base le framework CSS [Twitter bootstrap](http://getbootstrap.com/)
- Lorsque le thème a été développé, en 2012, c'est la version 2.2.1 qui était d'actualité.
- Par la suite, le thème a été mis à jour vers la version 2.3.0 car on en avait besoin pour les composants selectize (utilisé pour la consultation des index d'aide à la saisie) et pour handsontable (édition des tables d'autorité).
- Actuellement, bootstrap en est à la version 3.3.0, mais comme il n'y a pas de compatibilité ascendante entre la version 2 et la version 3, c'est difficilement envisageable de passer à la version la plus récente.
- Lors d'une version intermédiaire ([2.2.2](https://github.com/twbs/bootstrap/releases/tag/v2.2.2)), bootstrap a introduit des styles spécifiques pour l'impression.
- Ce sont ces styles qui posent problème.
- Ils font essentiellement [deux choses](https://github.com/stempler/bootstrap/commit/66fbed287d7a65b771e21e27cfb59f73e92fe5c2) : pour chaque lien de la page, ils impriment l'url de tous les liens (cf. scans faits par Olivier) et ils suppriment des choses qui, d'après bootstrap, ne sont pas utiles pour l'impression (couleur des titres, couleurs et images de fond, ombres, etc.). 

L'affichage des urls après chaque lien peut être désactivé en ajoutant dans la css prisme des règles spécifiques. Idem pour les titres des balises title. Par contre, les règles qui suppriment des choses ne peuvent pas être désactivées.

Lors de la discussion téléphonique avec Olivier, nous avons également convenu que la solution idéale serait, lors de l'impression, de n'avoir que la partie "utile" de la page et de supprimer : 

- la barre d'onglet et la présentation de la rubrique en cours
- la colonne latérale de gauche
- le menu de pied de page

Le logo Prisme qui figure en entête doit par contre être conservé pour avoir trace de la provenance de la page une fois imprimée.

Olivier signale également que si quelqu'un veut imprimer la page exacte telle qu'elle figure à l'écran, il s'agit alors d'une capture d'écran et non d'une impression classique.

**Comment by daniel-menard** [comment]
Deux autres problèmes à corriger : 

- à l'impression, bootstrap ajoute également un cadre génant autour des `blockquote` (résumés)
- pour les balises `abbr` il ajoute également le contenu de l'attribut title après l'abbréviation

**Comment by daniel-menard** [comment]
Les modifications décrites plus haut ont été faites, on a maintenant des impressions qui sont propres.

Remarques : 
- Pour la page d'accueil, le contenu principal est sur deux colonnes et ça "wrappe" au moment de l'impression (c'est dû à bootstrap et je ne peux pas corriger). Ce n'est pas pas top, mais ça reste lisible et je ne pense pas que la page d'accueil sera imprimée très souvent.
- J'ai fait le choix de conserver la sidebar optionnelle "topnews" qui figure au dessus de chaque contenu car je ne peux pas facilement choisir les pages sur lesquelles cela s'imprime ou pas (i.e. je la désactive complètement à l'impression ou pas du tout). Pour la liste des réponses, ce n'est pas trop utile d'avoir cette sidebar, car elle contient le formulaire et on a déjà le rappel de l'équation en dessous. Par contre, pour d'autres pages (blog, réseau...), ça contient de l'information utile qui a mon sens doit figurer sur la page imprimée. *Remarque* : sur la page "liste des réponses", le widget formulaire pourrait peut-être retourner dans l'entête comme sur les autres pages ?

Sur mon poste, j'ai testé avec : Chrome 40, FF 35 et IE 11. Si vous avez d'autres navigateurs ou d'autres versions, cela peut être intéressant de tester.

*Remarque :* Par défaut, IE a des marges de malade (plus de 2 cm de chaque côté) qui font perdre de la place sur la page. Mais même en réduisant les marges, on a avec IE une marge à droite qu'on ne peut pas supprimer (environ 3/4 cm chez moi).

Voici quelques exemples de pages imprimées (avec Chrome) : 

- Page d'accueil du site : 
![image](https://cloud.githubusercontent.com/assets/3940667/6232269/2e7e52fc-b6cb-11e4-9808-c8e840acb1f9.png)

- Présentation de la base Prisme : 
![image](https://cloud.githubusercontent.com/assets/3940667/6232424/22fca64e-b6cc-11e4-8e69-224fc073a8f6.png)

- Formulaire de recherche avancée : 
![image](https://cloud.githubusercontent.com/assets/3940667/6232230/e8c10e44-b6ca-11e4-9ff1-65445746dfdf.png)

- Liste des réponses : ![image](https://cloud.githubusercontent.com/assets/3940667/6232163/84c4728c-b6ca-11e4-9de5-82565c5e989b.png)

- Une notice : 
![image](https://cloud.githubusercontent.com/assets/3940667/6232199/b6fce5ea-b6ca-11e4-92d4-2163fce17723.png)

- Un article de blog : 
![image](https://cloud.githubusercontent.com/assets/3940667/6232249/083c66d8-b6cb-11e4-9828-ec802562f02c.png)

Ok pour vous ?

**Comment by daniel-menard** [comment]
J'aimerais bien fermer ce ticket... Avez-vous testé ?

**Comment by ocormont** [comment]
Après test, j'ai des impressions différentes sur le .net et le .org.

org
![capture org](https://cloud.githubusercontent.com/assets/5398792/6484297/1036d2fe-c27b-11e4-9635-05b88286b8d4.JPG)

net
![capture net](https://cloud.githubusercontent.com/assets/5398792/6484303/16d88d46-c27b-11e4-8075-57de0ce92f8a.JPG)

org
![capture org2](https://cloud.githubusercontent.com/assets/5398792/6484309/1d1aad6a-c27b-11e4-9333-4980617b280c.JPG)

net
![capture net2](https://cloud.githubusercontent.com/assets/5398792/6484312/214c1d56-c27b-11e4-8771-dde3b58cf3ca.JPG)

org
![capture net3](https://cloud.githubusercontent.com/assets/5398792/6484314/24e77794-c27b-11e4-90f1-c88745e71dfa.JPG)

net
![capture org3](https://cloud.githubusercontent.com/assets/5398792/6484316/29a908f6-c27b-11e4-8431-e24cce77484b.JPG)

A part ce problème, c'est ok pour la mise en forme .net

J'ai un autre problème sous firefox, l'affichage de la page en taille est différent. Plus grand sur le net que sur le org. Cela ne se produit pas sous chrome.
![capture org4](https://cloud.githubusercontent.com/assets/5398792/6484333/56b42542-c27b-11e4-81ce-dc052f8fdcb5.JPG)

![capture net4](https://cloud.githubusercontent.com/assets/5398792/6484336/59c430d8-c27b-11e4-8f3e-61784f627c95.JPG)

Et pour terminer, lors des tests, en faisant la même recherche, j'ai le même nombre de notices mais pas dans le même ordre. Voir capture résultats de recherche plus haut

**Comment by daniel-menard** [comment]
Je comptais en parler pendant notre réunion téléphonique de ce jour mais on n'a pas eu le temps.

Ce n'est pas trop utile de comparer le .net au .org : le code du .org n'a pas été mis à jour depuis très longtemps, donc effectivement, on n'a pas les mêmes affichages, le tri par pertinence du moteur n'est pas réglé pareil, etc. 

Donc la seule question, c'est "est-ce que tout est OK sur le .net ?"

Quand par la suite on fera la mise à niveau du .org, tout sera identique à ce qu'on a sur le .net.

Pour la différence de taille des polices entre firefox et chrome, est-ce que ce n'est pas simplement votre zoom (contrôle+molette de la souris) qui est réglé différemment ? Si vous réinitialisez (Ctrl+0), est-ce que ça résout le problème ? (je crois que vous aviez déjà eu un soucis comme ça, avant qu'on utilise github).

**Comment by ocormont** [comment]
Pour ma part, tout est ok sur le .net

Pour mon petit problème, cela se produisait sur le même navigateur.
En vérifiant le zoom ce matin, c'est ok.
Je pensais que si on faisait un zoom dans un navigateur, cela se répercutait sur l'ensemble des pages de ce navigateur. En l’occurrence non, il se souvient des pages avec zoom ou pas

**Comment by daniel-menard** [comment]
OK, je ferme donc ce ticket.

@Nicolas-L si vous faites des tests d'impression et qu'il y a des choses qui clochent, n'hésitez-pas à ré-ouvrir.
