### ISSUE TITLE
Vérification du dépouillement des revues

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#228]
La commission Producteurs vérifie le dépouillement des revues afin d'éviter des oublis de catalogage.
Je pense que la personne qui gère cela doit la faire de manière manuelle.
Voici une capture du début du fichier :
![capture4](https://cloud.githubusercontent.com/assets/5398792/6211775/05e639c4-b5de-11e4-9560-0a725887635e.JPG)

Est-il envisageable dans Docalist d'avoir un outil qui permet d'automatiser ce travail ?
Par exemple, si le numéro 43 de la revue Lien social est catalogué en saisie ou vie l'import, une alerte dit que le numéro 42 n'a pas été catalogué ?
Bien sûr, il n'est pas obligatoire que l'alerte soit donné en temps réel, mais de manière hebdomadaire.
Dans l'idéal, il faudrait que l'outil vérifie la périodicité de la revue afin de prévenir que le numéro 44 est sorti depuis 2 semaines et qu'il n'est pas encore catalogué. (Lien avec le répertoire des revues ?)

**Comment by daniel-menard** [comment]
Vu par téléphone avec Olivier : 

- c'est une bonne idée mais cela constitue un module de bulletinage à part entière, et c'est un projet en soi (pour gérer cela correctement, il faut prendre en compte un grand nombre de cas particuliers, et comme dit le proverbe, "le diable se cache souvent dans le détail")
- on a donc décidé de classe en "standby" (i.e. idée pour plus tard).
- par contre, il faudra voir si on ne peut pas simplifier le travail de la personne en offrant des équations de recherche pré-cablées (liste des notices d'un titre triées par numéro de volume et numéro de fascicule décroissants, par exemple)
