### ISSUE TITLE
Table extent : Document non paginé

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#229]
Lorsque nous saisissons une notice d'un document non paginé, si nous sélectionnons en valeur par défaut "Document non paginé" et que nous laissons la valeur vide, le champ n'est pas enregistré comme non paginé, le logiciel pense que ce champ est vide.
Une des solutions serait de mettre en valeur "np." afin que la valeur Non paginé apparaisse.

**Comment by daniel-menard** [comment]
C'est corrigé : le champ `extent` gère maintenant correctement le type d'étendue `no-pages - non paginé` et il sait que c'est une entrée qui ne prend pas de valeur et donc ne la filtre pas lors de l'enregistrement.

![image](https://cloud.githubusercontent.com/assets/3940667/6234072/f1aed718-b6d7-11e4-8cca-3ff77ba95b47.png)

Il n'y a pas besoin de saisir la mention "n.p." dans la valeur, elle est automatiquement générée lors de l'affichage de la notice, en fonction de ce qu'on a indiqué dans la table extent : 

![image](https://cloud.githubusercontent.com/assets/3940667/6234327/5ccd1256-b6da-11e4-974f-ab58d07226ed.png)

![image](https://cloud.githubusercontent.com/assets/3940667/6234094/24638ba4-b6d8-11e4-8b90-223ed6a706c6.png)
