### ISSUE TITLE
Liens internet : erreur mail

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#231]
Si le champ contient une adresse email, lorsque nous cliquons sur le mail, il ouvre le lien dans le navigateur, une erreur 404 est retourné.
http://www.documentation-sociale.net/tests/54/test@test.com

**Comment by daniel-menard** [comment]
C'est corrigé (et publié).

Le correctif consiste à ajouter le protocole [mailto:](https://fr.wikipedia.org/wiki/Mailto) lorsqu'une adresse e-mail est détectée (présence d'un signe `@`) et qu'elle ne contient pas déjà un protocole.

J'en ai profité pour améliorer le traitement des urls : les formats d'affichage du champ `link` ajoutent maintenant le préfixe `http://` si l'url ne mentionne pas de protocole (remarque : ce n'est pas une raison pour saisir des urls incomplètes). Ça gère également les liens ftp, etc.
