### ISSUE TITLE
Table Genre

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#232]
La commission Annuaire des sites souhaiterait ajouter le terme Site associatif.
Ce terme n'existe pas dans la table prédéfinie.
Cependant, l'entrée "Site institutionnel" pourrait correspondre

Voici les entrées concernant les sites

| Code          | Libellé                |
|---------------------------|---------------------------|
| personal-website          | Page perso                |
| blogging-platform         | Plateforme de blogs       |
| web-portal                | Portail d'entreprise      |
| social-networking-website | Réseau social             |
| community-website         | Site communautaire        |
| brand-website             | Site de marque            |
| video-sharing-website     | Site de partage de vidéos |
| photo-sharing-website     | Site de partage d'images  |
| web-presence              | Site de présence          |
| event-website             | Site événementiel         |
| corporate-website         | Site institutionnel       |
| online-shop               | Site marchand             |
| showcase-website          | Site vitrine              |

**Comment by daniel-menard** [comment]
La demande me semble légitime, j'ai donc ajouté l'entrée "Site associatif" dans la table des genres. 

La nouvelle entrée doit être comprise dans le sens "Site web présentant les activités et les services d'une association". 

J'ai également ajouté l'entrée dans la table personnalisée `prisme-genres-siteweb`.

*Important :* maintenant que le .org est ouvert, il faut penser à modifier les tables personnalisées à la fois sur le .net et sur le .org pour éviter qu'on se retrouve avec plusieurs versions (c'est ce que j'ai fait).
