### ISSUE TITLE
Documentation sur la syntaxe des requêtes de recherche

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#239]
Rédiger une documentation sur la syntaxe des équations de recherche gérées par le moteur.

**Comment by daniel-menard** [comment]
J'ai commencé à rédiger, mais c'est vite long et chronophage. Je pense qu'il faudra prévoir deux versions : une aide de la forme "référence rapide" qui explique les principaux opérateurs, un document plus long expliquant en détail comment tout ça fonctionne.

**Comment by daniel-menard** [comment]
J'ai créé un wiki docalist et j'ai rédigé plusieurs pages : 
- une [aide rapide sur la recherche](https://github.com/daniel-menard/prisme/wiki/Aide-%C3%A0-la-recherche)
- un [guide de référence sur la syntaxe des requêtes](https://github.com/daniel-menard/prisme/wiki/Syntaxe-des-requ%C3%AAtes)
- la [liste des champs interrogeables](https://github.com/daniel-menard/prisme/wiki/Liste-des-champ-interrogeables)
- la [liste des champs de recherche par défaut](https://github.com/daniel-menard/prisme/wiki/Champs-de-recherche-par-d%C3%A9faut)
- une doc sur [les différents types d'indexation](https://github.com/daniel-menard/prisme/wiki/Types-d'indexation)

Ça m'a pris pas mal de temps (près de 4 jours...) mais je pense que ça constitue une bonne base pour notre documentation.

Bonne lecture !

**Comment by ocormont** [comment]
J'ajouterai une précision avant la tableau de la page [aide rapide sur la recherche](https://github.com/daniel-menard/prisme/wiki/Aide-%C3%A0-la-recherche)
Comme c'est une aide rapide, il faudrait en parcourant savoir faire la recherche de suite. 
Cependant, il manque la syntaxe de l'url afin de pouvoir utiliser le tableau, donc peut être ajouter : après l'url, ajouter `/search?q=`+ votre recherche
