### ISSUE TITLE
Revoir les tables "fonction auteur" personnalisées Prisme

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#242]
Suite aux modifications faites sur la table relators-fr (#166), il faut vérifier et compléter les tables prisme personnalisées (`prisme-fonctions-auteur` et `prisme-fonctions-editeur`) : 

- pour chaque code, vérifier que le libellé dans la table personnalisée signifie la même chose que dans la table prédéfinie
- reprendre la définition qui figure dans la table prédéfinie
- ajouter les entrées dont vous avez besoin pour la grille film (c'est ce qui est à l'origine du ticket #166)

@Nicolas-L, @ocormont  : pouvez-vous vous en charger (il y a seulement 20 entrées en tout) ?

Une fois que ce sera fait, dites-le moi et j'intégrerai les modifs dans le code du plugin Prisme.

**Comment by ocormont** [comment]
je m'en occupe

**Comment by ocormont** [comment]
C'est fait.
Documents mis sur le drive avec les noms de fichiers `prisme-fonctions-auteur` et `prisme-fonctions-editeur`.
Il existe une table personnalisée `prisme-fonctions-auteur-film` que j'ai mis à jour aussi et qui a occasionné un bug, voir ticket #245

**Comment by daniel-menard** [comment]
J'ai mis à jour les tables prisme prédéfinies auteur/éditeur et j'ai intégré comme table prédéfinie la table audiovisuel.

Tout à l'air OK.
