### ISSUE TITLE
Workflow de validation des notices Prisme

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#244]
Lors de notre réunion téléphonique de ce jour, on a évoqué le workflow de validation des notices Prisme (producteur, correcteurs, etc.)

Les droits et les rôles WordPress semblent suffisants pour gérer l'essentiel, et on obtient des procédures beaucoup plus souples que ce qui est pratiqué actuellement (export par les producteurs, envoi au correcteur, correction, export et envoi du fichier corrigé, import par les producteurs).

Le seul point un peu délicat à gérer est lié au fait que le droit "correcteur" est tournant : une semaine c'est un producteur, la semaine suivant c'est un autre, etc. On a évoqué plusieurs hypothèses envisageables (changement des droits toutes les semaines, base tampon, compte correcteur unique, etc.)

Pour avancer sur ce point, je pense qu'il faudrait que vous rédigiez un document (directement sur google drive pour qu'on puisse y travailler à plusieurs) qui décrive tout ça. Ce sera un outil pour vous (doc de référence sur le workflow), mais aussi pour l'ensemble des producteurs qui auront une meilleure compréhension du nouveau système. Cela nous permettra aussi de vérifier si on a tout ce qui faut techniquement ou s'il y a des choses à développer ou à adapter.

Idéalement, il faudrait décrire le worflow actuel (en étant précis : qui fait quoi, combien de temps ça prend, bien lister chaque étape, etc.) et ensuite décrire le workflow qu'on aura avec docalist en présentant tous les avantages que ça donnera (fraîcheur de l'information, correction possible à plusieurs, validation au fil de l'eau, possibilité pour les producteurs de récupérer eux-mêmes les notices, possibilité de faire une sélection des notices récupérées, etc.)

Il faudrait ensuite lister les différentes hypothèses pour le système de correcteur tournant, lister les pour et les contre, et décider de l'option retenue.

Qui s'y colle ?...

Remarque : on aura besoin de ça pour lancer la saisie en ligne.

**Comment by ocormont** [comment]
Allez, je m'y colle...

**Comment by daniel-menard** [comment]
:-)

**Comment by ocormont** [comment]
J'ai commencé un document sur la procédure actuelle que j'ai envoyé à la com producteur pour rectification/ajout. Dès retour, je le mettrai sur le drive

**Comment by ocormont** [comment]
J'ai mis le document sur le drive : Workflow de validation des notices Prisme
J'ai ajouté un point sur l'échange de notices livres. J'ai fait de mémoire, j'ai demandé à la personne coordinatrice son avis/rectification sur cette partie

**Comment by ocormont** [comment]
Après échange, la procédure de création de notices ou d'import est celle ci :

Saisie en ligne : les producteurs saisissent directement dans la base Prisme du .org. Les notices sont mis `en attente de relecture`. Les correcteurs les publient.

Import vers Docalist : les notices importées le sont directement sur le .org. Leur statut est `en attente de relecture`. Les correcteurs les publient.

A faire : 
Actuellement, les notices importées sont visibles (statut publish). Il faut que les notices importées ont un statut `en attente de relecture`

**Comment by Nicolas-L** [comment]
Question : Base tampon - comme évoqué lors de la dernière réunion - ou saisie directe dans la base Prisme ?

**Comment by ocormont** [comment]
D'après mes souvenirs, pas de base tampon. Tout se fait dans la base principale

**Comment by Nicolas-L** [comment]
Et pas d'après les miens (j'en suis même certain)... mais est-ce vraiment pertinent si les statuts sont bien calés ?

**Comment by daniel-menard** [comment]
> Actuellement, les notices importées sont visibles (statut publish). Il faut que les notices importées soient `en attente de relecture`

J'ai ajouté une option qui permet, lors de l'import, de choisir le statut des notices importées. Par défaut, c'est l'option "En attente" qui est sélectionnée : 

![image](https://cloud.githubusercontent.com/assets/3940667/8213650/ba11e5d4-1523-11e5-820a-9bd9a8d1945c.png)

C'est plus souple que ce qu'on avait envisagé car ça permet de choisir (rechargement complet : statut publish, chargement d'une mise à jour : statut pending, test d'import perso : statut private, etc.)

**Comment by daniel-menard** [comment]
> Question : Base tampon

Ce que me disent mes souvenirs : initialement, on avait prévu de fonctionner avec une base tampon mais lors de la dernière réunion téléphonique (avant dernière ?) on en a discuté et nous sommes arrivés à la conclusion que c'était plus simple si la saisie était faite directement dans la base Prisme, ce qui donne le workflow décrit par Olivier (pas d'import/export d'une base à l'autre ni de conversions inutiles docalist->prisme->docalist susceptibles de faire perdre des données).

Le point qui bloquait, c'est que les notices puissent être importées avec un statut "en attente", pour les producteurs qui ne feront pas de saisie en ligne. C'est désormais réglé (cf. commentaire précédent) et les notices importées entreront ainsi dans le workflow standard de correction et de publication.

**Comment by Nicolas-L** [comment]
Oui vos souvenirs sont exactes. Quand je parlais de ce qu'on avait "évoqué" en réunion ou "annoncé" je parlais de la réunion qui s'est tenue avec les producteurs, en réponse à une de leur question/demande. A l'époque on ne devait pas être aussi au clair avec cette question. Ca risque de resurgir mais il n'y a rien de problématique. Pour en finir là dessus, on est d'accord : pas de base tampon.

Parfait pour les statuts des notices à l'import !

**Comment by daniel-menard** [comment]
Ok je comprend mieux.

Du coup, je pense que ce ticket peut être fermé ?

**Comment by Nicolas-L** [comment]
Juste pour avoir le Doc d'Olivier sous la main (Workflow de validation), je mets le lien en partage sur le Drive : https://drive.google.com/open?id=1CzuOiu5JFVr_XiHKjHvI7rbvkjZxx1-1dioj1z3sx1w&authuser=0

Et on ferme
