### ISSUE TITLE
Modification et Renommage  d'une table personnalisée activée dans une grille

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#245]
En modifiant la table personnalisée `prisme-fonctions-auteur-film`, j'ai remarqué que le nom de cette table n'était pas adéquat.
Je l'ai renommé `prisme-fonctions-auteur-audiovisuel` et modifié le libellé.
Cette table était déjà active dans la grille Film.
Ayant un doute, je vérifie en créant une notice Film, et un message d'erreur apparait
![capture](https://cloud.githubusercontent.com/assets/5398792/6503923/d1fe0928-c331-11e4-9b50-abecc95503d6.JPG)

Je vais voir dans les réglages de la grille de saisie Film. La modification du nom de la table a bien été faite, cependant, il y avait après la sélection de la table d'autorité !!! en rouge.
Je vais dans les réglages Formulaire de saisie Film. La modification du nom de la table a bien été faite, cependant, la valeur par défaut était sur un terme qui avait été éliminé de la table personnalisée. Je remets le bon terme.
Je vérifie en création de notice Film, tout était en ordre.

C'est un ticket juste pour signifier le problème résolu.

**Comment by daniel-menard** [comment]
C'est toujours compliqué, dans un logiciel, de gérer les erreurs qui peuvent survenir, les cas limites, etc.

J'avoue que là, c'est tout bonnement un cas qui n'est pas prévu mais qui devrait être géré. J'ai un peu regardé mais mine de rien, c'est un peu compliqué à gérer (cf. plus bas).

Dans la mesure où vous avez réussi à corriger vous même la situation, je ferme ce ticket en "stand-by" (i.e. un jour peut-être).

---

**Notes pour moi :**

En première approche, j'ai essayé de gérer ça dans le contrôle TableLookup : 
- lorsqu'on ouvre la table indiquée, catcher les exceptions
- si exception, interrompre et afficher un select classique (pas lookup) contenant les options actuelles de la notice

Mais ce n'est pas suffisant et il faudrait faire la même chose dans tous les contrôles qui utilisent des tables.

En fait ce n'est pas la bonne approche. 

Il faudrait que le logiciel : 

1. détecte quand une table est renommée et mette à jour toutes les grilles (ou autre) qui utilisent cette table

2. demande la "permission" avant de laisser l'utilisateur supprimer une table et interdire cette suppression si la table est déjà utilisée quelque part.

Techniquement, on ne veut pas créer de dépendances "en dur" de docalist-core vers docalist-biblio. 

Donc il faut gérer ça avec des actions et des filtres : 

1. Quand docalist-core renomme une table, déclencher une action "la table a été renommée" (paramètres : ancien nom, nouveau nom). 

  Dans docalist-biblio, intercepter cette action et, pour tous les types de toutes les bases, modifier les champs qui utilisent cette table.

2. Quand l'utilisateur supprime une table, déclencher un filtre "get-table-usage(la table)". 

  Si la table n'est pas utilisée, personne ne répond et le filtre retourne un tableau vide qui signifie "pas utilisée". Dans ce cas, on peut supprimer la table. 

  Dans docalist-biblio, intercepter ce filtre. Quand il est déclenché, examiner tous les champs de toutes les grilles de toutes les bases et ajouter dans le tableau une info disant que la table est utilisée (par exemple "champ xx de la grille yyy du type zzz de la base www"). 

  Quand docalist-core récupère ce tableau, afficher un message à l'utilisateur disant "vous ne pouvez pas supprimer cette table, elle est utilisée dans : (contenu du tableau)".
