### ISSUE TITLE
Notices issues d'une liste de périodiques

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#247]
Maintenant qu'on est au clair sur l'opérateur par défaut (#246), on peut s'amuser un peu avec les requêtes.

La question qui a généré le ticket #246 était : 

> est-ce possible de sélectionner toutes les notices issues de titres de périodiques que je couvre ?

L'interface du site n'est pas trop adaptée à la saisie de grosses équations de recherche car la zone de saisie est toute petite (une ligne).

Néanmoins, rien n'empêche de préparer sa requête dans un éditeur de texte (style "bloc notes") puis de la coller dans la zone de recherche.

Si on veut toutes les notices issues d'une liste de 30 titres de périodiques, il suffit alors de faire une requête du style : 

```php
journal.filter:(
        "Actualités sociales hebdomadaires (ASH)"
    OR  "Lien social"
    OR  "Empan (prendre la mesure de l'humain)"
    OR  "L'Information psychiatrique"
    OR  "L'Ecole des parents"
    OR  "Informations sociales"
    OR  "Neuropsychiatrie de l'enfance et de l'adolescence"
    OR  "Le Monde de l'éducation"
    OR  "Vie sociale et traitements"
    OR  "Sciences humaines"
    
    OR  "Esprit"
    OR  "Direction(s) (le mensuel des directeurs du secteur sanitaire et social)"
    OR  "Thérapie psychomotrice"
    OR  "Le Journal de l'action sociale"
    OR  "Enfances et psy"
    OR  "Dialogue"
    OR  "Le Monde diplomatique"
    OR  "Le Journal des psychologues"
    OR  "Alternatives économiques"
    OR  "Revue de droit sanitaire et social"
    
    OR  "Journal du droit des jeunes (la revue d'action juridique et sociale)"
    OR  "Réadaptation"
    OR  "La Revue française de service social"
    OR  "Perspectives psy"
    OR  "Les Cahiers de l'Actif"
    OR  "Métiers de la petite enfance"
    OR  "Bulletin de psychologie"
    OR  "Autrement"
    OR  "Sauvegarde de l'enfance"
    OR  "Revue française de pédagogie"
)
```

Pour faire cette requête, j'ai utilisé le champ `journal.filter`. 

On aurait pu utiliser le champ `journal` (sans filter), mais dans ce cas, le moteur aurait fait une recherche par phrase et aurait appliqué les traitements standards (minusculisation, suppression des accents, stemming...) aux différents mots.

Le fait d'utiliser `journal.filter` permet de faire une recherche exacte et qui en plus est beaucoup plus rapide à exécuter par le moteur (dans l'équation ci-dessus, c'est comme si on avait seulement 30 mots différents, ce qui n'est pas beaucoup).

Par contre, comme aucun traitement n'est effectué, il faut vraiment indiquer le titre exact du journal, *exactement comme il est saisi dans les notices* (en respectant les majuscules/minuscules, les accents, les espaces, etc.) En fait le plus simple consiste à faire un copier/coller du titre (depuis les facettes ou depuis les notices) plutôt que d'essayer de les taper.

> Remarque au passage : la distinction entre recherche par phrase et recherche par filtre peut aussi être utile pour détecter des titres de périodiques non normalisés.
>
> La requête `journal:"Revue française de pédagogie" -journal.filter:"Revue française de pédagogie"`, par exemple, permet de trouver les notices pour lesquels le nom du périodique contient les mots "revue", "française" et "pédagogie" (dans l'ordre) sans que pour autant ce soit le titre officiel (normalisé) indiqué dans le filtre ("Revue française de pédagogie"). Sur cette revue, par exemple, on a quelques variations liées à la présence ou pas du sous-titre de la revue.

Pour revenir à ma liste de 30 titres, on a une équation qu'on peut maintenant coller dans la petite zone de recherche du site. Le moteur se mange ça sans problème (on obtient 26930 réponses) et je suis convaincu que ça fonctionnerait tout aussi bien si on avait 50 ou 100 titres.

Après, on peut combiner cette équation avec d'autres critères. Par exemple, on pourrait ne vouloir que les notices publiées en décembre dernier (avant noël, histoire d'avoir une date précise au jour près) et dont les notices sont validées et corrigées (statut publié). Pour cela, il suffit d'ajouter les critères dans notre grosse équation (il n'est pas nécessaire de mettre des `AND` ou des `+` comme le "ET" est l'opérateur par défaut) : 

```php
date:[2014-12-01 TO 2014-12-24]
status.filter:Publié
journal.filter:(
    ...
)
```
(53 réponses)

La même technique peut être appliquée pour faire des sélections par éditeur, par producteur, pour indiquer une grande liste de mots-clés (récupération de notices sur une thématique donnée), etc.

Consultez le wiki pour connaître la [liste des champs utilisables](https://github.com/daniel-menard/prisme/wiki/Liste-des-champ-interrogeables).

Le champ `ref`, notamment, peut constituer un critère intéressant pour faire des récupérations régulières : si on sait que la plus grande notice qu'on a récupéré la dernière fois avait le numéro 77963, on peut facilement récupérer tout ce qui a été produit depuis : 

```php
ref:>77963
journal.filter:(
    ...
)
```
(112 réponses)

> Limites du système : tel que le site fonctionne, les équations de recherche exécutées sont transmises directement dans l'url de la page (en mode http "GET"). Si les requêtes deviennent très grosses, on peut atteindre des limites liées aux navigateurs car ceux-ci imposent une limite sur la taille maxi d'une url (2000 à 4000 caractères selon les navigateurs) et il faudrait alors changer la manière dont on transmet l'équation (passer en mode http "POST"). Cela dit on a de la marge, l'équation donnée au dessus, avec tous les espaces, ne fait que 1159 caractères

Vous me dites si tout cela fonctionne pour vous ?

**Comment by ocormont** [comment]
Cela fonctionne pour moi.

Cependant, votre remarque sur la distinction entre recherche par phrase et recherche par filtre peut aussi être utile pour détecter des titres de périodiques non normalisés me pose questions.

Votre exemple journal `journal:"Revue française de pédagogie" -journal.filter:"Revue française de pédagogie"` donne 35 réponses.
Le titre de la revue contient `Revue française de pédagogie (recherches en éducation)` , donc comme vous le disiez, un sous titre en plus.
Je pensais que la recherche `journal.filter:"Revue française de pédagogie"` interrogeait le champ journal et si dans une partie, il trouvait "Revue française de pédagogie" mais que l'expression était suivi ou précédé d'autres termes, le moteur donnait les résultats.

Ce qui aboutit à mon deuxième questionnement :
Lorsque nous aurons fait la base Périodique avec en url une requête préenregistré, il faudra faire attention à cette subtilité pour construire la requête, voir demandé à la com Producteur, de normaliser le champ.

**Comment by daniel-menard** [comment]
Précisions sur les remarques que vous faisiez le 10 mars : 

> Je pensais que la recherche `journal.filter:"Revue française de pédagogie"` interrogeait le champ journal et si dans une partie, il trouvait "Revue française de pédagogie" mais que l'expression était suivi ou précédé d'autres termes, le moteur donnait les résultats.

En fait on peut faire les deux, ça dépend du champ interrogé : 
- les champs de base (par exemple `journal`) sont indexés en plein texte. Dans ce cas, la recherche par expression signifie effectivement "*les notices qui contiennent l'expression indiquée dans le champ journal*", peu importe qu'il y ait des choses avant ou après.
- par contre, les champs filtres (par exemple `journal.filter`) sont indexés comme un token unique non analysé. Dans ce cas, l'expression signifie "*les notices dont le champ journal contient très exactement l'expression indiquée*".

Donc si on écrit `journal:"Revue française de pédagogie"` ça recherche toutes les variantes avec ou sans sous-titre et si on écrit `journal.filter:"Revue française de pédagogie"` ça ne recherche que ce titre exact et les notices qui ont un sous-titre en plus ne sortirons pas.

> Lorsque nous aurons fait la base Périodique avec en url une requête préenregistré, il faudra faire attention à cette subtilité pour construire la requête, voir demandé à la com Producteur, de normaliser le champ.

Ce n'est pas systématique...

Pour le champ journal, l'idéal serait effectivement qu'il soit normalisé. 

Dans ce cas, on peut alors utiliser `journal.filter` pour faire une requête sur le titre normalisé, ce qui donne une requête très efficace, mais très "stricte".

Si les titres ne sont pas normalisés, ou si on veut autoriser un peu de flou, ou si on ne veut pas trop s'embêter, une requête plein texte sur `journal` ira très bien et donnera en général les mêmes résultats.

Mais parfois, on n'a pas le choix, car certains titres peuvent être inclus dans d'autres titres... 

Par exemple, en santé publique, il y a une revue qui s'appelle [*Soins*](http://www.em-consulte.com/revue/SOIN/presentation/soins) mais il y a aussi une autre revue qui s'appelle [*Soins Cadres*](http://www.em-consulte.com/revue/SCAD/presentation/soins-cadres).

Si on fait une recherche `journal:"soins"`, ça n'ira pas, car ça sortira aussi les articles de la revue *Soins Cadres*. Si on veut uniquement les articles de la revue *Soins*, on est obligé, dans ce cas, d'utiliser `journal.filter:"soins"`.

Bref, ça dépend vraiment de ce qu'on veut faire, et ce qu'il faut retenir, c'est que le moteur permet de faire les deux, soit une recherche par expression classique, soit une recherche exacte. 

En espérant que ce soit plus clair...
