### ISSUE TITLE
La recherche simple plante avec certains caractères

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#256]
Lorsqu'on utilise la recherche simple et qu'on lance une recherche contenant des caractères "spéciaux", le programme plante (exemple : `creation:2003/03/31`).

C'est dû au fait que le thème Prisme n'encode pas correctement l'url générée lorsqu'il fait l'aiguillage entre "tout le site" et "base Prisme".

Pour l'exemple donné, ça génère une url de la forme `/search?q=creation:2003/03/31` alors que cela devrait générer `/search?q=creation%3A2003%2F03%2F31`.

En recherche avancée, cela ne se produit pas, car c'est le navigateur qui encode l'url.

**Comment by Nicolas-L** [comment]
On dirait que ce bug est résolu non ?

**Comment by daniel-menard** [comment]
oui, ça fait partie de tout les tickets que je dois mettre à jour :-)
