### ISSUE TITLE
Enregistrement notices Répertoire des revues

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#261]
Si on veut enregistrer une notice revue dans la base Répertoire des revues, un message d'erreur apparait : 
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid sequence group : dclrefrep-revues' in /var/www/documentation-sociale.net/plugins/docalist-core/class/Sequences.php:61 Stack trace: #0 /var/www/documentation-sociale.net/plugins/docalist-core/class/Sequences.php(151): Docalist\Sequences->name('dclrefrep-revue...', 'ref') #1 /var/www/documentation-sociale.net/plugins/docalist-biblio/class/Reference.php(468): Docalist\Sequences->increment('dclrefrep-revue...', 'ref') #2 /var/www/documentation-sociale.net/plugins/docalist-biblio/class/Pages/EditReference.php(413): Docalist\Biblio\Reference->beforeSave(Object(Docalist\Biblio\Database)) #3 /var/www/documentation-sociale.net/plugins/docalist-biblio/class/Pages/EditReference.php(95): Docalist\Biblio\Pages\EditReference->save(Array, Array) #4 [internal function]: Docalist\Biblio\Pages\EditReference->Docalist\Biblio\Pages\{closure}(Array, Array) #5 /var/www/documentation-sociale.net/wordpress/wp-includes/plugin.php(213): call_user_func_array(Object(Clo in /var/www/documentation-sociale.net/plugins/docalist-core/class/Sequences.php on line 61

**Comment by daniel-menard** [comment]
C'est bien un bug !

Il est lié à la présence du tiret dans le nom de la base (`rep-revues`). Je corrigerai le bug, mais en attendant, vous pouvez le contourner en donnant un nom plus simple à la base (par exemple `revues` tout court). 

*Remarque* : le slug est indépendant du nom, donc la base peut s'apeller `revues` en interne mais avoir un slug comme `repertoire-revues`.

Je viens de tester sur le .net et ça résout effectivement le problème. De manière générale, c'est mieux d'avoir des noms de bases courts.

---

Informations pour moi : 
- le bug vient du fait que le gestionnaire de base de données et le gestionnaire des séquences de numérotation automatique n'utilisent pas les mêmes règles de validation
- le gestionnaire de base autorise les caractères `a` à `z` et le tiret `-` (`AdminDatabases::validate()`).
- le gestionnaire de séquences, de son côté, autorise les caractères `a` à `z` et les chiffres (`Sequences::name()`)
- du coup, quand le gestionnaire de séquences voit une base qui a un tiret dans son nom, il "grogne".
- Travail à faire : harmoniser les deux. Peut-être `a`..`z`, `0`..`9` et `-`, ce qui permettrait d'avoir des chiffres dans les noms de base ?

**Comment by daniel-menard** [comment]
Le bug est corrigé, ce sera effectif lors de la prochaine publication.
