### ISSUE TITLE
Formulaire de saisie en paramétrage

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#265]
Dans le paramétrage des bases => Formulaire de saisie : 

Quelques difficultés pour rajouter des valeurs par défaut.
Exemples : 
- Base Site web => Champ "Indexation et résumé" => Résumé => Valeur par défaut
- Base Revues => Champ "Indexation et résumé" => Contenu du document => Valeur par défaut

Dans les deux cas, la deuxième valeur paramétrée est inchangeable (pas d'accès à la liste). Et si on duplique le champ, cette deuxième valeur est encore proposée sans pouvoir la changer. Et pas possible de saisir une valeur de la liste.

![capture](https://cloud.githubusercontent.com/assets/5398758/7812334/925c91de-03b1-11e5-9d35-a5edb00a8391.JPG)

Par ailleurs - est-ce mon navigateur ou la lenteur de ma connexion ? -, sur la plupart des exemples similaires (duplication de champ avec liste de valeurs), la liste n'apparaît pas toujours de manière systématique. Je dois taper les premières lettres ou sortir du champs et revenir dessus.

**Comment by daniel-menard** [comment]
Ce bug m'a bien occupé (depuis hier en fait), mais je pense avoir trouvé la solution.

### 1. Les lookups de fonctionne plus

C'est plus grave que ce que vous évoquez car en fait, cela ne concerne pas uniquement le paramétrage des bases, mais aussi la saisie des notices : dans les champs répétables, seul le premier lookup est utilisable (ou le dernier selon les cas)...

Après investigation, il s'avère que c'est une combinaison de deux problèmes distincts. Le premier est une étourderie récente mais le second est un problème qui a été introduit en septembre 2014. 

Du coup, je suis très surpris qu'on ne découvre le problème que maintenant car ça fait un moment que les lookups ne fonctionne plus correctement (si on se contentait d'ajouter de nouvelles valeurs, cela allait, mais si on voulait modifier une valeur déjà saisie dans une fiche existante, les lookups ne marchaient pas).

Quoiqu'il en soit, c'est maintenant corrigé et cela doit fonctionner correctement, que ce soit en saisie ou dans le paramétrage.

Merci de tester ça dans tous les sens pour confirmer.

### 2. Problèmes de lenteurs

De manière générale, je ne suis pas très content du module actuel de gestion des lookups car le composant de base utilisé ne me permet pas de faire ce que je veux. Du coup, ce n'est pas très optimisé : pour chaque lookup qui apparaît dans la grille, cela génère une requête ajax vers le serveur. 

Comme une grille standard peut facilement contenir une vingtaine de lookups (genres, supports, rôles, mots-clés, etc.), cela génère des requêtes *en rafale* sur le serveur. De plus, si on utilise plusieurs fois le même lookup (par exemple les étiquettes de rôle utilisées à la fois pour auteur et organisme), le système ne le détecte pas et des requêtes ajax différentes vont être générées. Enfin, si on a définit plusieurs valeurs par défaut pour un champ (par exemple plusieurs types de numéros ou de résumés), le système génère à nouveau des requêtes ajax pour chaque valeur !

Au final, lorsqu'on charge la grille de saisie, ce sont plusieurs dizaines de requêtes ajax qui sont envoyées en rafale au serveur.

De même, lorsqu'on "clone" un champ (i.e. on ajoute un auteur ou un résumé), cela génère deux requêtes ajax au serveur. Il faut ensuite récupérer les résultats, les traiter et les afficher, ce qui génère la lenteur constatée.

Tout cela n'est vraiment pas optimal et à plus ou moins long terme, je pense qu'il faudra complètement ré-écrire le module de gestion des lookups en utilisant un autre composant de base, ou en codant nous-même un composant spécifique. Mais comme c'est un gros morceau, je ne suis pas spécialement pressé de m'y attaquer...

En attendant, j'ai tout de même amélioré les choses, en permettant aux requêtes ajax générées par le serveur d'être mises en cache par le navigateur. 

Le fonctionnement général n'a pas changé, mais désormais, la réponse ajax retournée par le serveur pour un lookup est mise en cache par le navigateur. Du coup, lorsqu'on clone un champ, ou si on édite une autre notice, le navigateur a déjà en cache les entrées des tables et il n'a pas besoin de refaire de requêtes ajax pour les obtenir.

Cela améliore grandement les choses, mais avoir un cache pose toujours un problème : celui de la fraîcheur de l'information...

Pour les tables d'autorité, l'information n'est pas sensée changer toutes les cinq minutes (une fois qu'elles sont en place, on n'ajoute que rarement de nouvelles entrées), donc on peut se permettre d'avoir une durée de cache assez longue.

Pour le moment, j'ai mis une durée de cache de 7 jours. Cela signifie que si on ajoute ou qu'on modifie des entrées dans une table d'autorité, il peut s'écouler jusqu'à 7 jours avant que celles-ci ne soient visibles par les utilisateurs (le temps que le cache expire et que le navigateur fasse à nouveau une requête ajax).

En cas de besoin, on peut vider le cache du navigateur ou faire "F5" pour forcer un rafraîchissement complet de la page et être sûr d'avoir "la bonne version".

Par contre, pour la saisie sur index (mots-clés libres, noms propres, périodes...), on ne peut pas se permettre d'avoir une durée de cache aussi longue : si je saisis un nouveau candidat descripteur dans une notice et que j'enregistre, je m'attend à ce que celui-ci soit disponible lorsque je vais saisir la notice suivante (ou en temps cas peu de temps après).

Pour cette raison, j'ai mis dans ce cas une durée de cache de 10 minutes seulement.

Ces deux durées, 7 jours et 10min, sont un peu empiriques mais elles semblent fonctionner pas trop mal lors des tests que j'ai fait. On pourra bien sûr les changer comme on veut s'il faut affiner les réglages.

Pouvez-vous tester tout ça et me dire si c'est mieux ?

**Comment by Nicolas-L** [comment]
C'est mieux !
Les points que j'ai remarqué hier sont résolus. Idem pour la saisie.

**Comment by daniel-menard** [comment]
Ok, je ferme alors !
