### ISSUE TITLE
Affichage Panier/Export par Chrome

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#267]
Essentiellement sur Chrome (Mac et PC) : 

Sur la colonne de gauche - Panier et Export - les interlignes et la couleurs s'affichent par moment de cette façon : 

![capture](https://cloud.githubusercontent.com/assets/5398758/7836599/9c195042-0481-11e5-9d1e-63b0817b37e8.JPG)

Au lieu de ça (Capture Firefox) : 

![capture2](https://cloud.githubusercontent.com/assets/5398758/7836577/67def214-0481-11e5-93e6-26bad434d998.JPG)

**Comment by daniel-menard** [comment]
C'est corrigé : j'avais oublié de mettre à jour le numéro de version de la feuille de style et du coup les navigateurs utilisaient les anciens styles qu'ils avaient en cache.

![image](https://cloud.githubusercontent.com/assets/3940667/7837358/c4201990-0486-11e5-850e-1cc1c55ac2a2.png)
(chrome 43)
