### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#269]
En voulant préparer une requête pour la démonstration, j'ai remarqué quelques erreurs dans la recherche :
- J'ai construit cette recherche http://www.documentation-sociale.net/bases/prisme/recherche/?q=date:%3E2015-05-01 afin de pouvoir exporter les dernières notices.
Voyant le peu de réponses (10), j'ai vérifié par rapport aux dernières mises à jour que j'avais reçu.
(Cela à l'air de correspondre)
J'ai interrogé la base par rapport à un titre (Accès aux droits - l'éternel combat) en utilisant le moteur de recherche simple. 0 réponse

![capture](https://cloud.githubusercontent.com/assets/5398792/7837671/c5988f12-0488-11e5-8ec9-f3314f2aa9e5.JPG)

En interrogeant via la recherche avancée au titre, le document apparait
![capture1](https://cloud.githubusercontent.com/assets/5398792/7837701/044d69e4-0489-11e5-8229-db51e8077a7c.JPG)

En outre, si on retourne en Recherche avancée, un antislash se glisse avant l'apostrophe.
J'ai le même problème dans mes imports sous gediweb avec certaines notices. Cela pose des problèmes dans les recherches dans Gediweb

![capture2](https://cloud.githubusercontent.com/assets/5398792/7837784/7a11139c-0489-11e5-8fc3-79f691f547f4.JPG)

**Comment by daniel-menard** [comment]
Je pense avoir corrigé les deux problèmes de ce ticket.

### 1. Recherche exacte par titre

Ce problème est assez compliqué à expliquer, c'est lié aux modifications introduites dans le ticket #246 pour changer l'opérateur par défaut en "ET" et aux modifications introduites récemment pour supprimer automatiquement les mots-vides ([#241](https://github.com/daniel-menard/prisme/issues/241#issuecomment-105889972)).

En interne, docalist-search utilise une requête elastic-search de type [`query string`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) pour effectuer les recherches. Ce type de requête permet d'indiquer plusieurs champs et c'est ce qui est utilisé quand on fait une recherche "tous champs" sur le site.

Par exemple, quand on recherche "accès aux droits" (j'ai simplifié) en tous champs, je génère une requête du style : 
```JSON
{
    "query_string" : {
        "query" : "accès aux droits",
        "fields" : ["title", "author", "number", "etc."],
        "default_operator": "AND"
    }
}
```` 
(pour la liste des champs interrogés par défaut, cf. #240).

Intuitivement, on s'attend à ce qu'une requête de ce genre soit comprise comme : 

````JSON
    title:(accès AND aux AND droits) 
OR 
    author:(accès AND aux AND droits) 
OR  
    number:(accès AND aux AND droits) 
OR  
    etc.
````

Mais ce n'est pas ce que fait elastic-search. En fait il génère une requête du type : 

````JSON
    (title:accès OR author:accès OR number:accès OR etc.) 
AND 
    (title:aux OR author:aux OR number:aux OR etc.) 
AND 
    (title:droits OR author:droits OR number:droits OR etc.)
````

Autrement dit, il génère une "conjonction de coordinations" (des clauses "ou" combinées en "et") plutôt qu'une "coordination de conjonctions".

Maintenant que docalist-search gère les mots-vides, ceux-ci sont supprimés automatiquement des requêtes par elastic-search. Bien sur, ceux-ci ne sont pas supprimés dans tous les champs, mais uniquement dans les champs texte (titre, résumé, etc.) Dans des champs comme author ou number, il n'y a pas lieu de supprimer les mots-vides.

Et c'est là que ça se corse, car du coup, la requête générée par elastic-search devient : 

````JSON
    (title:accès OR author:accès OR number:accès OR etc.) 
AND 
    (author:aux OR number:aux)                                               <- problème
AND 
    (title:droits OR author:droits OR number:droits OR etc.)
````

Le traitement qui a été effectué est logique : 
- les mots "accès" et "droits" ne sont pas des mots-vides, donc ils ont été conservés dans tous les champs
- le mot "aux" est un mot vide pour tous les champs textes sauf pour author et number, donc on n'a gardé que ces deux là.

Le problème, c'est qu'une telle équation ne peut pas retourner de réponses : comme on a changé l'opérateur par défaut en "AND", toutes les clauses sont requises, et on ne trouvera jamais une notice avec "aux" dans le champ auteur ou dans le champ number.

Au passage, on voit bien que si l'opérateur par défaut est "OR" (ce qui est la valeur par défaut dans ES), il n'y a aucun problème.

**Résolution :**

Pour résoudre le problème, j'ai modifié la requête que j'envoie à elasticsearch : au lieu de générer une query_string portant sur plusieurs champs, je génère une query_string par champ et je combine tout ça en "OU" : 

```JSON
"query": {
    "bool": {
        "should": [
            {
                "query_string": {
                    "query": "Accès aux droits",
                    "default_operator": "AND",
                    "default_field": "title"
                }
            },
            {
                "query_string": {
                    "query": "Accès aux droits",
                    "default_operator": "AND",
                    "default_field": "author"
                }
            },
            {
                "query_string": {
                    "query": "Accès aux droits",
                    "default_operator": "AND",
                    "default_field": "number"
                }
            },
            "et ainsi de suite pour chaque champ"
        ]
    }
}
````

La requête générée est un peu "monstrueuse" (taille importante, beaucoup de répétition), mais ça fonctionne car cela génère bien l'équation qu'on souhaite avoir : 

````JSON
    title:(accès AND aux AND droits) 
OR 
    author:(accès AND aux AND droits) 
OR  
    number:(accès AND aux AND droits) 
OR  
    etc.
````

Pour elastic-search, la requête à exécuter est beaucoup plus lourde car il faut analyser la query_string autant de fois qu'on a de champs, mais lors des tests que j'ai fait, je n'ai pas noté de ralentissement notable.

Donc je pense qu'on peut considérer que le problème est réglé, même si j'imagine qu'on sera sûrement amené à y revenir...

### 2. Antislash devant les apostrophes

C'est une maladie de WordPress, c'est réglé.


Pouvez-vous re-tester tout ça et me dire si on peut fermer ce ticket ?

**Comment by ocormont** [comment]
Testé et approuvé.
Je ferme le ticket

**Comment by Nicolas-L** [comment]
Dans le même genre : les requêtes contenant des `:` dans le titre ne donnent aucun résultat

Ex : title:(Comité d'entreprise : création fonctionnement)

**Comment by daniel-menard** [comment]
Le problème, c'est que pour ElasticSearch, le ":" est un séparateur qui introduit une recherche par champ (comme quoi, y'a pas que dans la doc qu'on a des séparateurs).

Concrètement, quand il voit "entreprise : création", il pense qu'on veut rechercher le mot "création" dans le champ "entreprise". Comme ce champ n'existe pas (et qu'on est en "AND"), cela génère zéro réponse.

Dans la pratique, pour faire ce genre de recherche, il faut neutraliser le ":" (l'enlever).

On pourrait imaginer de pré-traiter la requête et de supprimer les chaines "espace suivi de deux-points" mais d'expérience, je sais que ce n'est jamais très bon de triturer les requêtes qu'on envoie au moteur.

A plus long terme, cela repose une question qu'on a déjà évoqué : est-ce que c'est une bonne chose d'utiliser les requêtes "query_string" pour la recherche sur le site (c'est puissant, on peut faire des équations et tout un tas de trucs, mais si on a une erreur de syntaxe - ou un ":" mal placé - ça plante).

ElasticSearch a un autre type de requête (simple_query_string) qui est moins puissant (pas d'opérateurs booléens ou de requêtes par range ou de trucs comme ça, juste + et -) mais qui lui e génère jamais d'erreur de syntaxe. A voir...
