### ISSUE TITLE
Suppression d'un utilisateur

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#271]
A la suppression d'un utilisateur, un message apparait me demandant que faire du contenu créé par cet utilisateur.
![sans titre-1](https://cloud.githubusercontent.com/assets/5398792/7838329/948f64f0-048c-11e5-9289-ad0ba48834fc.jpg)
Est ce valable pour les notices aussi ? que pour les articles ?
Pour ma part, je trouverai logique de laisser le nom de l'utilisateur, même si ce dernier a été supprimé.

**Comment by daniel-menard** [comment]
> Est ce valable pour les notices aussi ? que pour les articles ?

Je pense que c'est valable pour tous les types de contenus stockés dans WordPress : bases doc, articles, pages, commentaires, etc.

Si vous avez le temps, pourriez-vous faire un test pour vérifier que c'est effectivement le cas ?
- créez une notice/un post/un page avec le compte "oliviertest", 
- supprimez ce compte et réattribuez les contenus à un autre utilisateur
- regardez les trois types pour voir si le créateur/dernier modificateur ont été changés.

> Pour ma part, je trouverai logique de laisser le nom de l'utilisateur, même si ce dernier a été supprimé.

Oui, ça se défend, mais comme le créateur de la notice détermine également les droits afférants, WordPress a choisi de ne pas laisser traîner de "fantômes" d'utilisateur supprimés. 

Bref, c'est le code de WordPress et je n'ai pas la main la dessus...

**Comment by ocormont** [comment]
>- créez une notice/un post/un page avec le compte "oliviertest", 
- supprimez ce compte et réattribuez les contenus à un autre utilisateur
- regardez les trois types pour voir si le créateur/dernier modificateur ont été changés.

J'ai fait le test avec oliviercorrecteur qui a été supprimé. J'ai assigné les contenus à oliviertest.
Pour les trois types, le créateur est bien oliviertest

Peut être créer un compte générique si nous avons un jour cette problématique...
