### ISSUE TITLE
Affichage en saisie : Liste des Rôles

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#272]
Petite question quand on déroule la liste des rôles (table prisme-fonctions-auteur) dans le champ Auteur de la base Prisme ou de la base Test de saisie : 

On a les petites aides grâce au survol des `?` et `!`

Bref, quand on survol `!` on a des informations qui ne sont a priori pas dans la table et je me demandais d'où cela venait...

![capture](https://cloud.githubusercontent.com/assets/5398758/7838240/1fd324c6-048c-11e5-9e58-5f81004606a4.JPG)

Ici : `Changed MARC def; ...`

**Comment by daniel-menard** [comment]
Si si, c'est dans la table, le logiciel ne "créée" pas d'info tout seul !

Ce sont les colonnes standard "SN" (Scope Note = note d'application) et "HS" (history = historique) d'une table au format thesaurus, qui viennent en plus de la colonne "description" (dans le gestionnaire de table, il faut scroller horizontalement pour les voir) : 

![image](https://cloud.githubusercontent.com/assets/3940667/7838900/c81b91c4-048f-11e5-9864-6fec5e203a4e.png)

L'icône "?" correspond à la colonne description, l'icône "!" correspond à la colonne "SN" et la colonne HS n'est pas affichée.

Dans le cas de la table des étiquettes de rôle, la colonne SN a été utilisée à mauvais escient, ça devrait plutôt être stocké dans HS, concaténé au reste, car ce n'est pas de l'info très utile pour les utilisateurs (encore que...)

A changer si vraiment ça pose problème.

PS : c'est intensif les tickets aujourd'hui !!
