### ISSUE TITLE
Rôle et champ

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#273]
A la création d'un champ privé, je voudrais donner ce droit à tous les membres de Prisme, même ceux hors com producteur. Comment faire ?
![capture3](https://cloud.githubusercontent.com/assets/5398792/7838438/30f196e2-048d-11e5-984e-df9375ee6e5d.JPG)

Lister tous les rôles ? quel séparateur dans les rôles?
Création d'un rôle spécifique ?

Pour le moment, j'ai créé :
- rôle producteur.base-prisme : Créer une notice, modifier sa notice
- rôle correcteur.base-prisme : Créer une notice, publier toutes les notices de la base prisme...

**Comment by daniel-menard** [comment]
Je vois deux solutions possibles : 

**1. En passant par un nouveau rôle**

- Créer un rôle "Membre du réseau Prisme" (membre.prisme par exemple)
- Ajouter ce rôle à tous les comptes (en plus du rôle qu'ils ont déjà), à vous de voir si c'est "membre.prisme" le rôle principal et "producteur.base-prisme" le rôle secondaire ou l'inverse.
- Utiliser le nom du rôle comme capacité pour indiquer que le champ statut est réservé

**2. En utilisant uniquement une capacité spécifique**

- créer un nouveau droit (par exemple "voir_statut") et l'affecter à tous les rôles qui doivent avoir ce droit (producteur, correcteur, etc.) en utilisant l'option "add/remove capability" de Role Editor.
- utiliser ce droit pour limiter l'accès au champ status

Remarque : comme notre nouveau droit est "transversal" (i.e. pas rattaché à un type de contenu), Role Editor l'affichera dans la zone "Other Capabibilities" quand on affiche un rôle.


**Remarque :**

> Lister tous les rôles ? quel séparateur dans les rôles?

On ne peut pas lister plusieurs roles ou plusieurs droits dans la zone "Droit requis", donc il n'y a pas de notion de séparateur ou autre.

**Comment by daniel-menard** [comment]
Encore une remarque : 

Je n'ai rien trouvé dans WordPress qui indique s'il y a des règles à respecter pour le nom qu'on donne aux rôles et aux droits.

Cependant, je remarque que WordPress n'utilise que des noms très simples composés de lettres et du souligné (cf. https://wpfront.com/wordpress-plugins/user-role-editor-plugin/wordpress-capabilities/)

J'espère que ça ne nous posera pas de problème par la suite d'avoir utilisé des points et des tirets dans les noms de rôles...

Pour les droits, je suis presque sur que c'est limité, donc si vous retenez l'option 2, limitez vous aux lettres et au souligné (pas d'accents, de tirets, d'espaces, etc.)

**Comment by ocormont** [comment]
J'ai préféré utiliser l'option 1 car il y a pas mal de champs à protéger.
J'ai tester, cela fonctionne.
J'ai mi à jour les producteurs
