### ISSUE TITLE
Export des notices En attente de relecture

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#274]
Je suis un producteur qui a créé quelques notices.
Je voudrais les exporter dans ma base avant qu'elles ne soient corrigées et publiées.
Ces notices n'étant pas publiées, comment faire pour construire ma requête afin de pouvoir les exporter ?

**Comment by daniel-menard** [comment]
Avec les modifications apportées à docalist-search (#243), toutes les notices sont maintenant indexées, qu'elles soient publiées ou non (cela permet de répondre à ce genre de besoin et plus tard, cela permettra de faire du dédoublonnage, de la correction en série, etc.)

A l'interrogation, des filtres supplémentaires sont automatiquement ajoutés à la requête effectuée afin de garantir que chaque utilisateur ne voit *que les notices auxquelles il a accès*. Pour faire simple, cela ajoute un filtre du style `statut=publié OR createdby=<mon-login>` (dans la pratique, c'est beaucoup plus compliqué car cela tient compte des droits et capacités de l'utilisateur sur chacun des types de contenus interrogés, mais c'est ça l'idée).

Au final, quand un utilisateur fait une requête quelconque, il voit : 
- toutes les notices publiées (par n'importe qui)
- et toutes les notices dont il est le créateur (quelle que soit leur statut : brouillon, en attente, future, etc.)

Donc si l'utilisateur ne veut voir (pour les exporter) que les notices (créées par lui) qui sont en attente, il suffit de faire une recherche de la forme `status:attente` (ou, sous forme de filtre, `status.filter:"En attente"`).

Important : en faisant des tests pour répondre à ce ticket, j'ai identifié un vrai bug : le champ createdby n'est pas bien indexé (je vais faire un ticket séparé pour ça). Donc ça peut perturber les filtres mais le résultat attendu est bien celui que j'ai décrit plus haut.

Remarques : 
- Par construction, un utilisateur ne peut pas voir (ou exporter) les notices en attente faites par un autre utilisateur.
- Si c'est un besoin fréquent, ce serait utile d'ajouter la facette "statut de la notice" dans le widget : ça permettrait de faire la requête en un clic plutôt que de la taper.
- J'avais commencé à réfléchir à un widget "Mes liens" qui, un peu sur la même idée, permettrait de proposer à chaque utilisateur des liens utilitaires : mes notices, cette semaine, ce mois, en attente, à corriger (si c'est un correcteur), etc. A rediscuter.

**Comment by daniel-menard** [comment]
@ocormont Si vous avais le temps de tester, vous me dites si c'est ok en l'état ?

**Comment by ocormont** [comment]
J'ai encore du mal avec la recherche.
Je n'arrive pas à trouver mes notices en attente. J'ai mis comme équation : http://www.documentation-sociale.net/bases/tests-de-saisie/rechercher/?q=status:attente
J'ai aucune réponse

De même avec http://www.documentation-sociale.net/bases/tests-de-saisie/rechercher/?q=createdby=oliviertest
J'ai aucune réponse

Dans le même ordre d'idée, mais hors ticket, je n'arrive pas à combiner la recherche de 2 titres de revues. Nous en avions discuté par mail, il y avait un bug à l'époque. Je ne sais pas si il a été résolu.
Voici mon équation : http://www.documentation-sociale.net/bases/prisme/recherche/?q=&journal_filter=Actualit%C3%A9s+sociales+hebdomadaires+%28ASH%29&journal_filter=Lien+social

Je suis favorable à vos deux dernières remarques. Pour la V2 !

**Comment by daniel-menard** [comment]
**Notices en attente**

C'est ce que je craignais, comme le champ `createdby`n'est pas bien indexé (cf. remarque "important" dans mon commentaire ci-dessus), cela ne fonctionne pas si on n'est pas administrateur.

Je m'y colle...

**Combiner 2 titres de revue**
Je ne sais pas comment vous avez généré cette recherche, mais ça ne peut pas fonctionner (en modifiant directement l'url ?). 

Revoyez ce que j'expliquais dans le ticket #247 : il faut générer l'équation en indiquant explicitement qu'on veut du "OU" entre les titres (comme l'opérateur par défaut est passé en AND). Donc pour votre recherche, cela donnerait : 
```` 
journal.filter:("Actualités sociales hebdomadaires (ASH)" OR "Lien social")
````
(à taper dans la recherche rapide ou dans la zone "recherche libre" du formulaire de recherche avancée [exemple](http://www.documentation-sociale.net/advanced-search/?q=journal.filter%3A%28%22Actualit%C3%A9s+sociales+hebdomadaires+%28ASH%29%22+OR+%22Lien+social%22%29)).

Quand je teste, il me semble que ça retourne les bons résultats : 

- [liste des réponses (3446)](http://www.documentation-sociale.net/recherche/?q=journal.filter%3A%28%22Actualit%C3%A9s+sociales+hebdomadaires+%28ASH%29%22+OR+%22Lien+social%22%29)

**Comment by daniel-menard** [comment]
Maintenant que le ticket #277 est réglé, tout doit fonctionner comme attendu : 
- Connecté en tant qu'administrateur ou en tant qu'utilisateur ayant le droit de voir (read_private_xx_refs) et d'éditer (edit_private_xx_refs) des notices en statut privé (i.e. correcteur), je peux voir toutes les notices en attente quel qu'en soit l'auteur : 

  http://www.documentation-sociale.net/recherche/?q=status%3Aattente

  (4 réponses, 2 base prisme, 2 tests)

- Connecté en tant que producteur (dmdm ou oliviertest), je ne vois que les notices en attente dont je suis l'auteur : 

  http://www.documentation-sociale.net/recherche/?q=status%3Aattente 

  Pour le compte oliviertest, vous devez obtenir deux réponses, 1 dans la base prisme ("kyjguygbiu") et une dans la base tests ("ezezc fezrgregre gr").

- On peut également rechercher les notices créées par un utilisateur : 

  http://www.documentation-sociale.net/recherche/?q=createdby%3Aoliviertest

  (7 réponses : 4 tests, 1 article, 1 page, 1 base prisme)

  Remarques : 
    - dans l'url que vous aviez testé (cf. plus haut), il y avait une erreur. C'est `createdby:oliviertest`, pas `createdby=oliviertest`
    - attention : dans ce cas, c'est bien "créé par", une notice modifiée par oliviertest (mais créée par un autre utilisateur) ne sortira pas

Vous me dites si tout fonctionne pour vous ?

**Comment by ocormont** [comment]
J'ai fait quelques tests, cela fonctionne.

>Combiner 2 titres de revue
Je ne sais pas comment vous avez généré cette recherche, mais ça ne peut pas fonctionner (en modifiant directement l'url ?). 
oui, j'avais modifié l'url
