### ISSUE TITLE
Encore un tout petit

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#275]
ici : http://www.documentation-sociale.net/wordpress/wp-admin/options-general.php?page=docalist-search-settings&m=IndexerSettings

![cap](https://cloud.githubusercontent.com/assets/5398758/7839667/da816d62-0493-11e5-9ab4-97b96e4c4d56.JPG)

**Comment by daniel-menard** [comment]
euh... je ne vois pas la question. Ticket envoyé trop vite ?

**Comment by Nicolas-L** [comment]
Je ne comprends que la moitier de la phrase de la capture d'écran, jusqu'à `ou modifié et enlève`

**Comment by daniel-menard** [comment]
Ah je comprend. J'avoue que la phrase n'est pas claire et qu'il y a des gros problèmes d'accord !

Est-ce que la formulation suivante serait plus compréhensible : 

"Réindexer automatiquement les contenus créés, modifiés ou supprimés."

**Comment by Nicolas-L** [comment]
Oui mais ça laisse entendre qu'on réindexe les contenus supprimés

Je comprendrai mieux en reprenant à quelque chose près votre formulation initiale : "Réindexer automatiquement les contenus créés ou modifiés et retirer les contenus supprimés"

**Comment by daniel-menard** [comment]
C'est fait :-)
