### ISSUE TITLE
Création Rôle et Compte de la commission producteur

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#276]
J'ai créé deux nouveaux rôles :
- producteur.base-prisme : Création de notice, Modification de ses notices, suppression de ses notices sur la Base Prisme et Tests de saisie.
- correcteur.base-prisme : Tous les droits sur la Base Prisme et Tests de saisie

J'ai créé un compte pour tous les membres de la commission producteur. Je les ai mis dans le groupe producteur.base-prisme. 
De même, je les ai invité sur notre liste de diffusion.

Pour le moment, je n'ai pas d'utilisateurs (à part un compte de test) avec le rôle correcteur.base-prisme. J'attends la réunion du 29 afin de voir quel workflow sera choisi.

**Comment by daniel-menard** [comment]
ça me parait bien, a un détail près.

Pour tester, j'ai utilisé mon compte "dmdm" et je lui ai attribué le rôle "producteur.base-prisme". Quand ensuite je me connecte avec ce compte, je peux créer une notice dans la base prisme et la base test en utilisant l'option qui figure dans le menu "Créer" de la barre d'administration : 
![image](https://cloud.githubusercontent.com/assets/3940667/7855784/86d98032-0524-11e5-931a-2f30357e0350.png)

Mais je ne peux pas accéder au back-office de WordPress (option "tableau de bord"), j'obtiens le message "Vous n’avez pas les droits suffisants pour accéder à cette page." : 
![image](https://cloud.githubusercontent.com/assets/3940667/7855799/a78193f6-0524-11e5-80bd-8541b35deecd.png)

Ni modifier mon profil utilisateur : 
![image](https://cloud.githubusercontent.com/assets/3940667/7855999/053abed6-0526-11e5-88df-e4c63429afb8.png)

Pour éviter ces erreurs, il faut attribuer le droit "read" aux rôles : 
![image](https://cloud.githubusercontent.com/assets/3940667/7855859/08f60c16-0525-11e5-8da1-f8431561791b.png)

Ce droit est une capability standard de wordpress, c'est vraiment le droit de base (en gros cela signifie "j'ai un compte"). Donc en gros, il faut que tous les rôles que vous créez aient ce droit.

Ça rajoute des options dans le menu de wordpress (dont le tableau de bord qui ne sert à rien, on est bien d'accord), et donc l'interface pour les producteurs sera un peu moins dépouillée, mais bon, ça reste assez simple tout de même : 

![image](https://cloud.githubusercontent.com/assets/3940667/7856022/310f045e-0526-11e5-9b2a-f00d88147982.png)

**Comment by ocormont** [comment]
Merci.
J'ai corrigé

**Comment by daniel-menard** [comment]
J'ai vu que le rôle "producteur.base-prisme" disposait des droits en écriture à la fois sur la base Prisme et sur la base Tests de saisie.

Mais en fait, on ne veut pas que les producteurs saisissent dans la base Prisme : dès qu'on va faire un rechargement complet, les données seront écrasées.

Donc je pense qu'il vaudrait mieux n'avoir les droits en écriture que sur la base Tests de saisie, cela éviterait que des notices soient saisies par erreur dans la mauvaise base ? (idem pour correcteur)

Remarque : peut-être aussi qu'on pourrait changer le libellé de la base test (par exemple "saisie en ligne" ou un truc dans le genre), cela ferait moins test et plus mise en production ?

**Comment by ocormont** [comment]
Pour moi, je pensais que nous n'allions faire que des mises à jour de notices dans la base prisme, plus de rechargement complet.
Si cela n'est pas possible, renommer la base me semble judicieux. 
C'est possible de modifier le nom d'une base déjà existante ?

**Comment by daniel-menard** [comment]
Si on est sur qu'il n'y aura plus de rechargement complet, alors ok... mais est-on sur ?

> C'est possible de modifier le nom d'une base déjà existante ?

Le nom (nom de code interne de la base), non, on ne peut pas le changer, par contre on peut changer le libellé.

**Comment by daniel-menard** [comment]
Olivier a fait tout le travail de création des rôles et des droits, il me semble que ce ticket peut désormais être fermé.
