### ISSUE TITLE
Bug Mot clé

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#282]
Saisie sur le .net Base Prisme par Laurence Serbouti

Elle a mis des mots clés sur une notice
![capture2](https://cloud.githubusercontent.com/assets/5398792/7915625/1c46ebf2-087f-11e5-8a41-b8bf7bc7f0af.JPG)

A l'affichage, AAH apparait
![capture](https://cloud.githubusercontent.com/assets/5398792/7915633/2f0e9406-087f-11e5-8fdc-85dd0a8243ad.JPG)

En testant avec des mots clé différents, je ne reproduit pas le bug.
En mettant les mêmes clé que Laurence, le fantôme réapparait

**Comment by daniel-menard** [comment]
Il est marrant, ce bug : on dirait que le programme a décidé d'attribuer l'Allocation Adulte Handicapé à tout le monde ! Ce serait bien si c'était aussi simple :-)

Plus sérieusement, c'est corrigé.

Le bug était assez subtil : il n'apparaissait que si on utilisait le mot-clé "CODE" et uniquement celui-là (quoique si on avait eu un mot-clé "LABEL", on aurait eu le même souci). 

En fait, dans le code il y avait une "collision" avec la colonne "code" de la table thesaurus : au moment de traduire le code en libellé, le module qui formate les mots-clés testait "code=code" et comme c'est toujours vrai, il sortait la première entrée trouvée (AAH).

Le problème a été corrigé dans le module de formatage, mais j'ai également fait l'inventaire complet du code pour voir si ce genre de problème pouvait survenir ailleurs : normalement, c'est corrigé partout.
