### ISSUE TITLE
Fichier d'export

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#283]
Lors de la génération du fichier d'export, 

- Ajout de ,PA dans le TY

- Ajout de l'information du libellé dans le résumé
L'information doit être entre crochet [ ], 

![capture](https://cloud.githubusercontent.com/assets/5398792/7932804/26ed0112-091b-11e5-8ef0-249dee600f0f.JPG)

**Comment by daniel-menard** [comment]
C'est corrigé : 

- Le code `PA`  correspond à "Document imprimé" mais cette entrée ne figurait pas dans la table `prisme-conversion-media`.
- J'ai modifié le programme d'export pour que le type de résumé figure entre crochets et non entre parenthèses.
- J'en ai profité pour supprimer les espaces superflus (après "MECS" sur la copie d'écran ci-dessus).

![image](https://cloud.githubusercontent.com/assets/3940667/7955362/0b4a71e8-09d8-11e5-83f5-ac746dfc957b.png)
