### ISSUE TITLE
Table number

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#284]
Très petit détail : 

J'ai remarqué que sur la table prédéfinie "Types de numéros - numbers" certains labels commencent par une majuscule, d'autres par une minuscule (ex : Supplément ; Numéro ; volume n° ; disque n°).

Est-ce qu'il ne faudrait mettre partout la même chose pour homogénéiser l'affichage des notices ?

![capture](https://cloud.githubusercontent.com/assets/5398758/7940053/b90701d2-094e-11e5-8f6a-24cd59bfbe8a.JPG)

Par extension : la table "prisme-number" est concernée par ma remarque

**Comment by daniel-menard** [comment]
> Très petit détail

Pas tout à fait ! En examinant ce ticket, j'ai repéré plusieurs problèmes : 

**1. Effectivement, les libellés utilisés ne sont pas homogènes**

J'ai corrigé la table docalist prédéfinie `numbers`. 

J'avais le choix entre mettre une majuscule partout ou tout mettre en minuscules : j'ai choisi de tout mettre en minuscules (sauf les sigles et acronymes comme ISBN ou EAN).

La raison, c'est que les entrées sont destinées à être concaténées et cela me semble logique d'avoir `tome, volume, numéro` plutôt que `Tome, Volume, Numéro`.

J'ai appliqué les mêmes corrections sur la table prisme `prisme-numbers`.

**2. Il y avait deux petites erreurs dans la table**

- une typo dans la description de l'entrée `ISBN`.
- le format d'affichage de l'entrée `official-number` était incorrect.

J'ai fait également les corrections dans la table Prisme.

**3. Les grilles Prisme n'utilisent pas toujours le "bon" format d'affichage**

La table `numbers` contient deux colonnes "libellé" : 

![image](https://cloud.githubusercontent.com/assets/3940667/7956199/a56c19a6-09de-11e5-8451-c8ac9131afb1.png)

La colonne `label` est utilisée pour "décrire" l'entrée. C'est cette colonne qui est affichée en saisie : 
![image](https://cloud.githubusercontent.com/assets/3940667/7956232/e29db4c4-09de-11e5-8999-320849d83488.png)

Les libellés utilisés dans la colonne `label` doivent être explicites et doivent permettre de distinguer clairement les différentes entrées de la table afin d'éviter de se tromper d'entrée lors de la saisie.

L'autre colonne, `format` est destinée à être utilisée en affichage. Dans ce contexte, on peut se permettre d'être moins explicite, d'utiliser des abréviations et d'avoir des libellés non uniques car le contexte d'affichage (type de notices, etc.) permet de savoir à quel type de numéro on a affaire.

Lorsqu'on paramètre le champ `number` dans les grilles d'affichages (affichage court et affichage long), plusieurs formats d'affichage sont proposés : 

![image](https://cloud.githubusercontent.com/assets/3940667/7956629/774c12a8-09e1-11e5-8cf9-d29c45705a5e.png)

Selon moi, c'est toujours le format indiqué dans la table d'autorité (le premier proposé) qui devrait être utilisé (c'est le cas dans les grilles prédéfinies de docalist). On obtient alors le formattage suivant et non pas celui que vous avez dans votre copie d'écran : 

![image](https://cloud.githubusercontent.com/assets/3940667/7956522/a007fa6e-09e0-11e5-9e15-5d79f9886758.png)

Dans les grilles Prisme, le format utilisé n'est pas toujours le même (ça varie d'un type à l'autre, d'une grille à l'autre, etc.). 

Je pense qu'il faudrait faire un inventaire complet et vérifier/indiquer partout le bon format : pourriez-vous vous en charger ? (faire nouveau ticket svp)

En attendant, je ferme ce ticket qui ne concernait "que" le problème des majus/minus dans les libellés.
