### ISSUE TITLE
Recherche avancée et format Date

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#286]
Le format date du formulaire de recherche avancée à l'air d'être au format AAAAMMJJ.
Donc si on fait une recherche limitée à une année, cela ne fonctionne pas

**Comment by daniel-menard** [comment]
Vu par tél le 05/06 : pour le moment, il faut faire une recherche par "range", par exemple `[2014 TO 2015]`.

La raison, c'est que ElasticSearch gère des dates précises à la seconde près (en fait, c'est même à la micro-seconde). Quand on indique une date incomplète, ES convertit la date au début de la période indiquée : 
- 2015/06/09 est traitée comme le 9 juin à 00h00
- 2015/06 est traitée comme le 1er juin à 00h00
- 2015 est traitée comme le 1er janvier à 00h00

Quand on recherche simplement `date:2015`, ES recherche donc les notices qui ont été publiées le 1er janvier à minuit précise, et bien sur, cela génère zéro réponses. C'est la même chose si on fait une recherche sur un mois précis sans indiquer le jour (par exemple `date:201506`).

De son côté, une recherche par range telle que `[2014 TO 2015]` est comprise comme "publiée entre le 1er janvier 2014 à 00h00 et le 1er janvier 2015 à 00h00", ce qui donne bien les réponses attendues.

On pourrait imaginer, lors de l'indexation, "d'injecter" les dates qu'il faut pour que ES trouvent les notices. Par exemple, si on a une notice publiée le 2015/06/09, on pourrait indexer `2015/06/09 00h00`, `2015/06/01 00h00` et `2015/01/01 00h00`.

Dans ce cas, une recherche simple telle que `date:2015` ou `date:2015/06` fonctionnerait et retournerait les réponses souhaitées.

Mais le problème, c'est que dans ce cas, on ne peut plus distinguer entre les "vraies" dates et les dates injectées. 

Par exemple, si on veut uniquement les notices publiées en janvier 2015, on aura également les notices publiées en février, en mars, etc. puisqu'on aura injecté à chaque fois la date du premier janvier.

Idem si un producteur veut récupérer les notices saisies entre le 01/06 et le 05/06 : il récupérera également toutes les notices saisies en juin.

Donc pour le moment, la seule solution possible est d'utiliser les recherches par range.
