### ISSUE TITLE
Question Rôle

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#287]
Avec mon identifiant Test qui a un rôle "Abonné" j'ai accès à la publication de notices (sur bdd PRISME et "Test de saisie" uniquement). Est-ce normal ? ... Je ne vois pas où ce rôle est paramétré. Subscriber n'a visiblement pas ces droits.

**Comment by daniel-menard** [comment]
> Est-ce normal ?

Votre compte `nicolastest` a comme rôle principal "abonné" mais il a comme rôle secondaire "correcteur.base-prisme". Les droits du compte sont "la somme" des droits des rôles donc ce compte est correcteur, ce qui explique que vous ayez tous les droits sur les bases.

![image](https://cloud.githubusercontent.com/assets/3940667/8052400/a2a975a8-0e87-11e5-97cc-5ea53e44bda4.png)

> Je ne vois pas où ce rôle est paramétré.

Seuls les administrateurs peuvent modifier les droits. Connectez-vous avec votre compte admin et modifiez le profil du compte `nicolastest` (menu utilisateurs). Vous pourrez alors modifier le rôle principal du compte (milieu du formulaire) : 

![image](https://cloud.githubusercontent.com/assets/3940667/8052494/5cd3403a-0e88-11e5-90eb-31753268bbe6.png)

et/ou le rôle secondaire (ajouté par le plugin de gestion des droits, apparaît en fin de formulaire) : 

![image](https://cloud.githubusercontent.com/assets/3940667/8052530/94211dfa-0e88-11e5-9aee-9e1396b467c9.png)

De leur côté, les droits associés à chacun des rôles se paramètrent via le plugin de gestion des rôles (menu Roles, all roles).

**Comment by Nicolas-L** [comment]
Of course ! le Secondary, Merci d'avoir pris le temps de la réponse, j'avais zappé ce détail !
