### ISSUE TITLE
MAJ BDD 2015 semaine 23

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#288]
Voici l'extrait de la bdd pour la semaine 23 : https://drive.google.com/file/d/0ByXmpIQEtIYxSTJLZmllcW9TNW8/view?usp=sharing

**Comment by Nicolas-L** [comment]
J'ai chargé le fichier de 54 notices. Par contre, sur ces notices (et seulement sur ces notices), les numéros attribués repartent de 1. Le compteur ne part pas du numéro +1 de la dernière notice créée ce qui génère des doublons dans les identifiants.

Ex : http://www.documentation-sociale.net/bases/prisme/3/

Est-ce que j'ai zappé une étape dans la procédure d'import ?

**Comment by Nicolas-L** [comment]
La semaine 24 est disponible dans le dossier : https://drive.google.com/folderview?id=0ByXmpIQEtIYxfmNzVmlNQS1zTmZ4b2lvSUpseXNuVU5vWnBfTDZUY2pGQW1Kbnh6RzNnUlE&usp=sharing

Chargée sur le .ORG, même problème. 3 références par identifiant.

**Comment by daniel-menard** [comment]
Lors de l'import du fichier, le programme d'import gère le champ REF de la façon suivante : 

- si le champ REF est vide, le programme alloue un numéro de REF à la notice (plus grand numéro dans la base + 1)
- si le champ REF est renseigné, le numéro est importé tel quel.

Dans le cas présent, les fichiers de mises à jour ont un champ REF renseigné, donc le programme l'importe : 

![image](https://cloud.githubusercontent.com/assets/3940667/8128700/f031c312-1101-11e5-8270-b8c90e5697ef.png)

Pour que cela fonctionne correctement, il faudrait : 
- soit que les fichiers à importer soient générés avec un champ REF vide ;
- soit que ce soit les "vrais" numéros de REF qui soient exportés et non pas un numéro bidon commençant à 1 à chaque export.

Si aucune de ces deux options n'est possible, il faudra modifier le programme d'import et greffer une option pour ignorer le champ REF qui figure dans les notices importées.

PS : en attendant que le problème soit résolu, il faudrait supprimer les notices qui ont été mal importées (et ne pas en importer d'autres). Je ne vois pas trop comment le faire en automatique sans supprimer aussi des notices valides... Est-ce envisageable que vous les supprimiez manuellement ?

**Comment by Nicolas-L** [comment]
Je vais supprimer les notices récemment importées et faire un essai d'import en enlevant le numéro du champ REF. Je demanderai ensuite si les fichiers peuvent nous être envoyés avec un REF vide.
Je vais aussi supprimer les notices créées par les producteurs qui auraient du être saisies dans la base de test (statut en attente).

**Comment by Nicolas-L** [comment]
Bon, j'ai réimporté en effaçant le n°REF, a priori, les numéros qui sont attribués suivent mais j'avoue être encore perplexe : sur 78153 notices le dernier numéros s'envole à 78737... et il y a des numéros vides entre ces deux chiffres (ex : 78700).
Je pense qu'il faut plutôt demander à Anne de faire en sorte que le fichier REF respecte le numéro d'entrée réel.

En tout les deux fichiers faisaient 52+21=73 notices

**Comment by Nicolas-L** [comment]
En fait le dernier numéro REF de l'import de mai est 78695, donc bien au delà du nombre de notices.

**Comment by Nicolas-L** [comment]
Voici le lien vers la MAJ des semaines 23, 24 et 25 : https://drive.google.com/file/d/0ByXmpIQEtIYxTU9GRF9NQjFiQVU/view?usp=sharing

Avec ces histoires de numéro de REF, j'ai demandé qu'on me donne un fichier unique de ces trois dernières semaines pour que les notices suivent les numéros de la base complète.

La maj du .NET est faite : 85 notices

**Comment by daniel-menard** [comment]
La mise à jour a été faite sur le .org lors de la mise à niveau du site (#301)
