### ISSUE TITLE
Corbeille

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#289]
En mettant à la corbeille les dernières notices importées (action en cours), si je clique sur la corbeille pour avoir la liste, on a un "Fatal error" après la 9ème notice.

![capture](https://cloud.githubusercontent.com/assets/5398758/8129432/65d78db6-1109-11e5-9ca4-ead1184038f0.PNG)

**Comment by daniel-menard** [comment]
C'est corrigé (cependant je n'ai pas pu vraiment re-tester car la corbeille a été vidée depuis)
