### ISSUE TITLE
Type de notice et champ Colloque

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#290]
Le champ colloque est manquant dans les types de notices :
- Article
- Numéro de périodique

**Comment by daniel-menard** [comment]
Le champ `event` a été ajouté dans les grilles docalist prédéfinies pour les types `article` et `periodical-issue` et dans les grilles Prisme personnalisées pour la base Prisme et la base Tests de saisie (après les titres, à personnaliser si besoin).

![image](https://cloud.githubusercontent.com/assets/3940667/8215148/7145c9fa-152e-11e5-985b-98aab641fb84.png)
