### ISSUE TITLE
Format d'export Prisme

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#291]
Il manque certains types de formats d'export actuellement.
Il faudrait ces différents formats :
- Format 2011 Caractères riches : tous les champs sont exportés en minuscule accentué
- Format 2011 Majuscule : Les champs Auteurs (AU AS AUCO) et descripteurs (DOM DE CE GO HI DENP) sont exportés en majuscule non accentuée 
- Format 2014 Caractères riches : tous les champs sont exportés en minuscule accentué
- Format 2014 Majuscule : Les champs Auteurs (AU AS AUCO) et descripteurs (DOM DE CE GO HI DENP) sont exportés en majuscule non accentuée

**Comment by daniel-menard** [comment]
J'ai presque bouclé ce ticket. Quelques questions/confirmations rapides pour que je finalise : 

**Mise en maju de AU et AS (`author`)**

*Pour le moment, je ne transforme en majuscules non accentuées que la partie "nom" de l'auteur.*
1. Faut-il également majusculiser le prénom ?
2. Faut-il également majusculiser l'étiquette de rôle ?
3. J'ai fait un cas particulier pour "et al." pour qu'il ne soit pas mis en maju. Ok ?

**Mise en maju de AUCO (`organization`)**

*Pour le moment, je ne met en maju que la partie "nom" de l'organisme.*
4. Le sigle est censé être en maju, donc rien à faire
5. faut-il mettre la ville en maju ?
6. faut-il mettre le pays en maju ?
7. faut-il mettre le rôle en maju ?

**Mise en maju de ED (`editor`)**

*cf. discussion d'hier sur la mailing-list.*
8. faut-il convertir ED/EDLIEU en maju ?
9. si oui quels éléments ? (nom/ville/pays/rôle)

**Mise en maju de DOM/DE/CD/GO/HI/DENP (`topics`)**

*Pour le moment, ce  qu'on a fonctionne de la façon suivante : si l'option "tout maju" est sélectionnée, exporter le code du mot-clé, sinon, exporter le libellé tel qu'il figure dans la table.*

*Pour le champ DE, cela fonctionne car dans le thesaurus, on a des codes en tout maju et des libellés en riche.*

*Par contre pour les autres champs cela ne fonctionne pas : DOM a des codes en riche, les autres sont sur index.*
10. Faut-il réellement convertir tout en tout maju sans accents ?

**Comment by ocormont** [comment]
>Mise en maju de AU et AS (author)
1. Faut-il également majusculiser le prénom ?

Non
>2. Faut-il également majusculiser l'étiquette de rôle ?

Non
>3. J'ai fait un cas particulier pour "et al." pour qu'il ne soit pas mis en maju. Ok ?

Oui


Mise en maju de AUCO (organization)

>Pour le moment, je ne met en maju que la partie "nom" de l'organisme.
4. Le sigle est censé être en maju, donc rien à faire

Oui

>5. faut-il mettre la ville en maju ?

Non

>6. faut-il mettre le pays en maju ?

Non

>7. faut-il mettre le rôle en maju ?

Non

>Mise en maju de ED (editor)
cf. discussion d'hier sur la mailing-list.
8. faut-il convertir ED/EDLIEU en maju ?

Non, les caractères riches étaient déjà la règle

>Mise en maju de DOM/DE/CD/GO/HI/DENP (topics)
10. Faut-il réellement convertir tout en tout maju sans accents ?

Oui

**Comment by daniel-menard** [comment]
Toutes les modifs ont été faites et publiées sur le .net : 

1. **La liste des formats d'export proposés a été simplifiée**

  Les formats Prisme qui manquaient ont été ajoutés, les formats dont prisme n'a pas besoin ont été supprimés (j'ai juste conservé docalist json/xml qui me sont utiles) : 

  ![image](https://cloud.githubusercontent.com/assets/3940667/8205236/1c5c5efc-14ef-11e5-9ea2-4e790c5d04d0.png)

2. **Les auteurs, les organismes et les mots-clés sont maintenant convertis en majuscules non accentuées pour les formats "maju"**

  Voir commentaire précédent.

3. **J'ai désactivé les options "envoyer par mail" et "compresser le fichier"**

  Elles apparaissaient dans l'écran "choix du format" mais elles ne sont pas encore implémentées (à réactiver une fois que ce sera fait).

4. **Le navigateur propose désormais d'enregistrer le fichier d'export sur le poste local plutôt que de l'afficher à l'écran**

  L'affichage direct était un moyen simple (pour moi) de débugger le module d'export, mais c'est plus pratique de récupérer directement le fichier contenant les notices (jusque là, il fallait faire un copier/coller dans le bloc-notes comme évoqué sur la mailing list).

  Cela risque néanmoins de générer un problème : l'encodage des caractères (accents et autres notamment). Le fichier qui est généré est encodé en [UTF-8](https://fr.wikipedia.org/wiki/UTF-8) sans [BOM](https://fr.wikipedia.org/wiki/Indicateur_d%27ordre_des_octets) : c'est le standard actuel sur toutes les plateformes pour encoder un texte.

  Mais je ne suis pas sûr que les (vieux) logiciels documentaires vont savoir gérer ça. Jusque là, les producteurs faisaient un copier/coller des notices exportées vers le bloc notes windows, ce qui devait, je pense ré-encoder au passage les caractères en [ISO-8859-1](https://fr.wikipedia.org/wiki/ISO_8859-1).

  Bref, il va falloir refaire des tests et voir si les accents sont correctement importés dans les logiciels doc. Si ce n'est pas le cas, il faudra encore adapter l'export Prisme...

**Comment by daniel-menard** [comment]
Olivier a fait un test d'import et comme je m'y attendais, les caractères riches sont mal importés. 

Il faut donc modifier l'export Prisme pour que cela génère un fichier encodé en ISO-8859-1.

**Comment by daniel-menard** [comment]
C'est fait, les formats Prisme génèrent désormais des fichiers ansi (i.e. ISO-8859-1).

J'ai greffé ça sous forme d'option, comme ça on pourra facilement changer ou proposer des formats alternatifs si les logiciels utilisés par le réseau se mettent à gérer de l'utf-8 par la suite.

Olivier : si vous avez le temps, merci de faire un test (mais je suis assez confiant sur le fait que c'est résolu).

**Comment by ocormont** [comment]
Ca marche
![capture](https://cloud.githubusercontent.com/assets/5398792/8228479/50dc41ae-15af-11e5-9bc4-a50951a490b8.JPG)

**Comment by daniel-menard** [comment]
Merci d'avoir testé. Du coup, je ferme ce ticket.

**Comment by daniel-menard** [comment]
Je réouvre car certains caractères ne sont pas bien convertis : 

![image](https://cloud.githubusercontent.com/assets/3940667/8241086/760c888c-1607-11e5-89a7-bbbee7056864.png)

(signalé par Sophie Arnaud sur la mailing list).

Dans la copie d'écran, c'est "l'apostrophe incurvée" qui est mal convertie. Le texte contient : 

![image](https://cloud.githubusercontent.com/assets/3940667/8241118/bc53d3d6-1607-11e5-9b8c-16ba627b9290.png)

et non pas : 

![image](https://cloud.githubusercontent.com/assets/3940667/8241158/f86c1180-1607-11e5-914b-af72fd8327bf.png)

Il y a certainement d'autres caractères qui sont mal convertis dans la mesure où l'utf-8 peut encoder plus d'un million de caractères différents alors que l'ansi n'en possède que 256...

**Comment by daniel-menard** [comment]
C'est corrigé : l'export effectue désormais de la "translittération" pour convertir les caractères unicodes vers leur équivalent ANSI le plus proche.

Comme indiqué plus haut, la conversion ne peut pas être parfaite, mais le convertisseur fait de son mieux : il traduit les apostrophes typographiques en apostrophes simples, les ligatures comme `œ` en `oe`, etc.

Remarques : 
- Dans la majorité des cas, les diacritiques qui n'existent pas en ANSI sont remplacées par la lettre de base équivalente (`Ā` est remplacé par `A`, `Ů` est remplacé par `U`, etc.)
- Dans certains cas (caractères en langue étrangères), la conversion peut donner lieu à une combinaison accent/lettre de base. Par exemple, le caractères `Ć` sera convertit en `´`+ `C`, le caractère `Ŝ` sera remplacé par `^` + `S`, etc.
- De même, le symbole `€` qui n'existe pas en ISO-8859-1 (il existe sous windows mais pas dans l'ISO qui a été standardisé avant que l'euro n'existe) sera converti en `EUR`.

De manière générale, tous les caractères "courants" utilisés par Prisme devraient être correctement convertis.

**Comment by ocormont** [comment]
En faisant un test d'export au format 2011 :
- problèmes de certains caractères : pas d'erreur dans gediweb
- Champ NO : problème avec les intitulés (table ?)
bibliogr. devient bibliographie
Résumé : abstract
![capture0](https://cloud.githubusercontent.com/assets/5398792/8250426/fb183ce4-1673-11e5-9de0-fdab90f071f4.JPG)

**Comment by daniel-menard** [comment]
> Champ NO

Je viens de faire un test, je n'arrive pas à reproduire...

J'ai exporté la référence REF=103 dans la base test. Dans l'export 2011, j'obtiens `pp. 43-46, résumé en français, bibliographie`, ce qui me semble correct (ce sont les libellés qui figurent dans la table `Prisme-format`).

Pourriez-vous me donner les n° de ref (et la base) des notices que vous avez exportées dans l'exemple ci-dessus pour que j'essaie de reproduire le pb.

**Comment by ocormont** [comment]
Le Sociographe (recherches en travail social)	 n.11, mai 2003, 8 notices

**Comment by daniel-menard** [comment]
Ok, j'ai compris : ce n'est pas un problème d'export.

Si on affiche une des notices, on a le même problème : 

![image](https://cloud.githubusercontent.com/assets/3940667/8251344/13961b12-167c-11e5-8775-bf2eef53cceb.png)

En fait on a une erreur dans la table `format` (table des étiquettes de collation) le code correct pour "résumé en français" devrait être `abstract-fre` mais dans la table, on a `abstract-fra` (c'est une erreur que j'ai dû introduire quand j'ai travaillé sur le ticket #106).

Comme on a procédé par recopie, la table personnalisée `Prisme-format` a la même erreur.

Par contre le programme d'import injecte la bonne étiquette, `abstract-fre`.
 
Du coup, on se retrouve avec des notices qui contiennent `abstract-fre`, mais à l'affichage ou à l'export, il ne sait pas comment convertir ça (puisque cela ne figure pas dans la table) et il affiche le code tel quel.

Pour corriger immédiatement le problème, j'ai modifié la table personnalisée avec le bon code. Ça résoud immédiatement le problème en affichage : 

![image](https://cloud.githubusercontent.com/assets/3940667/8251447/e68433f6-167c-11e5-9af1-831a4503ad34.png)

et en export : 

![image](https://cloud.githubusercontent.com/assets/3940667/8251496/4ce3ed62-167d-11e5-8c2d-690a2693f63e.png)

**Important :**
La correction faite sur la table personnalisée fait que les notices importées de la base centrale vont être affichées et exportées correctement. Par contre on va avoir le problème inverse avec toutes les notices qui on été saisies en lignes et qui contiennent "abstract-fra" (la mauvaise étiquette qui était proposée jusque là par les lookups en saisie)).

**Travail à faire :**
- [ ] Corriger la table prédéfinie docalist (`abstract-fra` -> `abstract-fre`)
- [ ] Vérifier les autres codes langues (`abstract-XXX`)
- [ ] Même problème pour la langue des sous-titres (on a `subtitles-fra`)
- [ ] Corriger la table ` prisme-conversion-format` (on a plusieurs fois `subtitles-fra` dans les combinaisons utilisées pour gérer les résumés multi-langues, cf. #106).

**Comment by daniel-menard** [comment]
PS : vous pouvez refaire un test d'import gediweb, svp ?

**Comment by ocormont** [comment]
Je n'ai pas pu faire le test, j'ai une erreur lorsque je fais ma recherche
![capture](https://cloud.githubusercontent.com/assets/5398792/8252164/4d489ebe-1683-11e5-9704-52129fb5f5d2.JPG)

**Comment by daniel-menard** [comment]
Je viens de voir ça... j'ai dû faire une fausse manip sur #301. Grr.

**Comment by daniel-menard** [comment]
J'ai attrapé un coup de chaud mais c'est résolu...

**Comment by ocormont** [comment]
Oui, je viens de faire un F5 !
Test import réussi.
Par contre, Prisme utilise les abréviations sur ce champ
bibliogr., ill. ...
Et là nous avons l'intitulé complet.
Il faut avoir les abréviations de cette table Prisme - Table de conversion des étiquettes de format

**Comment by daniel-menard** [comment]
Ce ticket concernait la finalisation des formats d'export Prisme, c'est fait (on a les 4 formats prisme, les champs sont convertis en maju, les problèmes d'accents ont été résolus).

Je ferme donc ce ticket et je vais en créer un nouveau pour le point que vous soulevez dans votre dernier commentaire.
