### ISSUE TITLE
Grille livre : le champ ISBN n'a pas de type

### ISSUE THREAD

**Issue by daniel-menard** [daniel-menard/prisme#296]
(problème signalé par Laurence Serbouti sur la mailing-list)

Dans la grille livre, le champ `number` a le libellé "ISBN / EAN" mais n'a aucune valeur par défaut dans la zone `type`.

Si on saisit un ISBN mais qu'on laisse la zone `type` vide, l'isbn n'est pas exporté car le format d'export Prisme ne sait pas à quel type de numéro il a affaire : 

![image](https://cloud.githubusercontent.com/assets/3940667/8229917/98b34746-15bb-11e5-8f4a-05a1b839406b.png)

Je pense qu'il faudrait modifier la grille de saisie pour que le champ ait une valeur par défaut avec type=isbn, ou bien modifier le libellé pour qu'on n'ait pas l'impression que le type "isbn" est implicite.

Olivier : pourriez-vous vous en charger, svp ?

**Comment by ocormont** [comment]
C'est fait sur les bases Tests de saisie et Prisme

**Comment by daniel-menard** [comment]
Merci Olivier !

Je pense qu'on a le même problème dans la grille Mémoire ou thèse pour le champ "Spécialité du diplôme" : comme le libellé est "le bon" (et non pas "autres titres"), on ne pense pas à saisir le type de titre...

Il y a sûrement d'autres champs sur lesquels cela se pose, il faudrait balayer les champs structurés pour voir...

Du coup, je ré-ouvre ce ticket.

**Comment by ocormont** [comment]
C'est fait sur le .org et la base prisme du .net
Je clos donc ce ticket
