### ISSUE TITLE
Présentation des mots clés sur la facette (front)

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#297]
Question concernant la présentation des Mots clés au "sens large" - liste de la table prisme-topic- dans la facette. La facette affiche les codes et non les labels remis en majuscule.

Du coup les domaines qui ont un code différent du label (pas explicite) s'affichent sous cette forme :
![capture](https://cloud.githubusercontent.com/assets/5398758/8229501/c315a294-15b7-11e5-9d59-f39622fce332.PNG)

Idem pour les "Informations documentaires" (site web)

Ne faudrait-il pas fonctionner avec les tables Thésaurus comprises dans la table prisme-topic comme avec la table thésaurus Prisme. A savoir, un code en MAJU et un libellé Riche ?

**Comment by daniel-menard** [comment]
Le problème ne concerne pas que les domaines, c'est beaucoup plus large que ça.

En fait, c'est l'ensemble des mots-clés qui n'est pas bien indexé : actuellement, c'est systématiquement le code des mots-clés qui est indexé et non pas le libellé. 

Pour les mots-clés du thésaurus Prisme, cela n'était pas gênant car le code et le libellé sont identiques à la casse près. Cependant, on voit bien dans les facettes que c'est le code (tout maju, pas d'accents) qui est affiché et non le libellé (c'est dommage, on s'est embêté à faire une version riche du thésaurus) : 

![image](https://cloud.githubusercontent.com/assets/3940667/8238624/350cc4e2-15f7-11e5-8a93-d405212f8a73.png)

Avec les domaines, le problème devient beaucoup plus visible, car il n'y a pas d'équivalences code/libellé comme pour le thésaurus. On obtient du coup la copie d'écran du commentaire précédent.

J'ai modifié l'indexeur pour que les mots-clés soient correctement indexés, ce qui fait qu'on a maintenant les libellés et non les codes dans les facettes : 

![image](https://cloud.githubusercontent.com/assets/3940667/8240608/31be9998-1604-11e5-879b-adc759a1db0e.png)

Cela fonctionne également pour les domaines : 

![image](https://cloud.githubusercontent.com/assets/3940667/8240660/997cbd62-1604-11e5-9d2d-6b01745cf1a0.png)

Remarque : j'ai également modifié la feuille de style css du site car un traitement spécial avait été mis en place pour réduire la taille des mots-clés en tout maju.

**Comment by daniel-menard** [comment]
Je ferme ce ticket comme c'est réglé, même si cela n'empêche pas de retravailler et d'harmoniser les codes de la table domaines.
