### ISSUE TITLE
Affichage des notices "en attente" d'un producteur

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#298]
Un producteur a créé une notice avec un statut "en attente de relecture"
Il a voulu récupérer sa notice en faisant une équation status:attente
Aucun résultat ne sort
![capture1](https://cloud.githubusercontent.com/assets/5398792/8231778/221942c4-15cb-11e5-9e62-80f23fb7019a.JPG)

![capture2](https://cloud.githubusercontent.com/assets/5398792/8231780/25b168b2-15cb-11e5-940e-ca204b58c9f3.JPG)

Je test en créant une notice "en attente" avec mon compte test ayant un rôle producteur
![capture3](https://cloud.githubusercontent.com/assets/5398792/8231836/70858c56-15cb-11e5-9682-ac05e6de623c.JPG)

je fais une équation status:attente, et j'ai des résultats
![capture4](https://cloud.githubusercontent.com/assets/5398792/8231858/8a78407c-15cb-11e5-8555-831e9f1c5938.JPG)

Nous avons les mêmes rôles, la même équation, et cela donne un résultat différent.

Une différence que j'ai remarqué, en me connectant avec le compte agaussel, il y avait un panier en cours.
J'ai testé avec le compte lserbouti, même erreur et il y avait un panier actif

**Comment by daniel-menard** [comment]
Je pense avoir corrigé le problème. 

La requête `status:attente` me donne désormais : 

- deux réponses pour votre compte de test (test de récupération de notice, ezezc fezrgregre gr)
- une pour A. Gaussel (Les nouvelles technologies au service de l'enfance)
- cinq pour Laurence

Le problème venait des filtres "cachés" qui sont appliqués aux requêtes (quand on fait une requête, le système ajoute des filtres pour que chacun ne voit que les notices auxquels il a droit).

Il y avait un bug dans le filtre "créé par moi" : au lieu d'utiliser le champ brut (`createdby.filter`), on utilisait le champ générique (`created`) sur lequel est appliqué du stemming.

Du coup cela ne fonctionnait pas si le stemming générait un terme différent du login réel (agaussel -> agausel -> zéro réponses).

On utilise désormais le bon filtre, ce qui corrige le problème.

Je vous laisse tester et fermer si tout est ok ?

*Remarque panier :*

En fait, cela n'avait rien à voir avec le fait d'avoir ou non un panier non vide dans le compte. 

Néanmoins, comme expliqué par téléphone, on peut se retrouver dans la situation où on a panier non vide mais quand on l'affiche, on a aucune réponses ou pas toutes. 

L'explication, c'est que le panier stocke uniquement les numéros d'enregistrement internes des notices sélectionnées et lorsqu'il affiche "votre panier contient x notices", il compte simplement le nombre de numéros qu'il a. 

Mais si les notices en question ont, depuis, été supprimées dans la base, il ne peut pas les retrouver quand on demande à afficher le panier.

En occurrence, c'est ce qui s'est passé avec le bug #288 : Nicolas a supprimé de la base Prisme des notices de test qui avaient été mises en panier sur certains comptes.
