### ISSUE TITLE
Export Table Genre

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#303]
A l'export, le champ Genre contient les termes anglais
![capture](https://cloud.githubusercontent.com/assets/5398792/8277539/2b92040c-18c4-11e5-8246-f0598f59ac6c.JPG)

**Comment by ocormont** [comment]
nouveau test avec tous les genres
ref : 78783
![capture](https://cloud.githubusercontent.com/assets/5398792/8277909/5348dda6-18c7-11e5-92a6-2314dfc7cc24.JPG)

**Comment by daniel-menard** [comment]
En fait, c'était juste la table de conversion utilisée lors de l'export (`prisme-conversion-genre`) qui était incomplète.

Je viens de mettre à jour la table en ajoutant toutes les entrées qui figurent dans les tables : 
- `prisme-genres-article`
- `prisme-genres-book`
- `prisme-genres-film`

Pour les entrées des deux premières tables, je génère à l'export le libellé indiqué dans le fichier excel qui décrit le bordereau Prisme.

Pour la dernière (film), plusieurs entrées n'existent pas dans le bordereau Prisme officiel. Pour la table de conversion, j'ai utilisé pour l'export le même libellé que celui qui figure dans la table d'autorité personnalisée, dites-moi s'il y a des libellés à changer.

Cela concerne les entrées suivantes : 

```csv
;;------------------------------------------------------------------------------
;;Genres utilisés dans la table prisme-genres-film
;;------------------------------------------------------------------------------
Clip;clip;
Colloque;colloquium;
Débat;debate;
Entretien;conversation;
"Fiction documentaire";documentary-fiction;
"Film d'animation";animated movie;
Humour;humour;
"Journée d'étude";study-day;
Magazine;magazine;
Spectacle;show;
"Stage technique";technical-course;
Théâtre;theatre;
```

Remarque : 
- à ce jour la table `prisme-conversion-genre` est complète : toutes les entrées proposées en saisie figurent dans la table de conversion. Si de nouvelles entrées sont ajoutées dans les tables en saisie, il faudra penser à mettre à jour la table de conversion.
- On va probablement avoir des problèmes similaires sur d'autres tables de conversion (supports, etc.) Je manque de temps pour faire une comparaison exhaustive maintenant, on ouvrira de nouveaux tickets quand on le détectera. De manière générale, si un terme est mal converti à l'export alors que d'autres le sont, penser "table de conversion incomplète".
