### ISSUE TITLE
Requêtes avec caractère accentués et résultats sur les articles et les pages

### ISSUE THREAD

**Issue by Nicolas-L** [daniel-menard/prisme#51]
Les résultats des requêtes sur un même mot avec ou sans ses caractères accentués ne sont pas identiques.
Exemples de requêtes : 

- reseau : 2 pages renvoyées
- réseau : 18 pages et 7 articles renvoyés

- these : rien
- thèse : 3 pages et 1 article renvoyés

En revanche, les résultats sont identiques pour ce qui concerne la bdd biblio

**Comment by daniel-menard** [comment]
Le travail fait dans le cadre du ticket #268 a permis de résoudre ce vieux ticket (un an et demi !)

Les articles et les pages WordPress ont maintenant un indexeur spécifique qui utilise la classe d'indexation standard. Cela permet de garantir qu'il n'y a pas de différence entre l'indexation des bases de données et l'indexation des autres contenus WordPress.

Désormais, une requête sur tout le site sur `réseau` ou `thèse`, qu'ils soient écrit avec ou sans accents donne bien le même nombre de réponses dans tous les cas.
