### ISSUE TITLE
Titre d'une revue

### ISSUE THREAD

**Issue by ocormont** [daniel-menard/prisme#86]
Ceci est plus un ticket de réflexion.
La commission producteur a créé l'année dernière un champ STP correspondant au sous titre de la revue. Cette création ayant été faite après validation du bordereau, Docalist ne gère pas ce champ. Cependant, cette problématique du sous titre n'est pas propre à Prisme et pourrait être intéressante.
La commission réfléchit actuellement au maintien du champ ou à d'autres possibilité...
L'intérêt de ce champ est qu'il peut donner des indications à l'usager sur le contenu éditorial de la revue. L'inconvénient est que nous avons constaté une modification fréquente de ce sous titre par certains éditeurs.
Si il existe une base des revues, peut-être mettre ici l'info du sous titre et l'injecter dans les notices de la revue ? A voir avec les possibilités d'export.

**Comment by daniel-menard** [comment]
Je pense que ce ticket peut être fermé.

- Dans le bordereau Prisme 2014, STP n’existe plus (cf. #135 + e-mails échangés avec les membres de la commission producteur en octobre).
- Il reste bien sur la gestion des relations filles/mère dans les notices docalist, mais c'est plus large que le titre de la revue.
